### ISSUE TITLE
[BUG] Chat 函数有bug

### ISSUE THREAD

**Issue by huajianmao** [QwenLM/Qwen-7B#100]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

加载模型后，先调用`chat(..., stream=True)`，然后再调`chat(..., stream=False)`的时候，会报错。
``` shell
AttributeError: 'GenerationConfig' object has no attribute 'do_stream'
```

可能是因为stream里会设置`self.__class__.generate` 和 `sample_stream`的原因。

### 期望行为 | Expected Behavior

两者行为应该相互独立

### 复现方法 | Steps To Reproduce

``` python
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers.generation import GenerationConfig

model_id = "Qwen/Qwen-7B-Chat"
tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="cuda", trust_remote_code=True).cuda().eval()
model.generation_config = GenerationConfig.from_pretrained(model_id, trust_remote_code=True)

query = "Hi"
history = None

model.chat(tokenizer, query, history, stream=True) # <--------- OK
model.chat(tokenizer, query, history) # <--------- It will fail

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by huajianmao** [comment]
可能可以这么改：

``` python
if stream:
    ....
else: # <---------- L999
    self.__class__.generate = PreTrainedModel.generate  # disable stream <---------------------
    ...
```

**Comment by huajianmao** [comment]
另外，`stop_words_ids`在stream模式下是无效的。

**Comment by HongyuJiang** [comment]
遇到了同样的问题

**Comment by huajianmao** [comment]
建议添加自动测试用例等，提高模型代码质量

**Comment by fyabc** [comment]
@huajianmao 您好，该问题已经在最新的HuggingFace repo中修复，您可以更新到最新版本，然后重新尝试一下
在调用时，请将`model.chat(..., stream=True)`调用替换为`model.chat_stream(...)`，前者已废弃

**Comment by JianxinMa** [comment]
> @huajianmao 您好，该问题已经在最新的HuggingFace repo中修复，您可以更新到最新版本，然后重新尝试一下 在调用时，请将`model.chat(..., stream=True)`调用替换为`model.chat_stream(...)`，前者已废弃

更好的做法是不是做下兼容，让 `model.chat(..., stream=True)`等价于`model.chat_stream(...)`？
