### ISSUE TITLE
[BUG] 关于Qwen-7B-Chat本地推理，对某个问题的回答，回复内容均为异常

### ISSUE THREAD

**Issue by jiaigo** [QwenLM/Qwen-7B#101]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior
`response, history = model.chat(tokenizer, "你的模型参数是多少", history=["你好"])`
1.
![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/92b5cab4-8a21-4356-b559-2b9709ce647d)
2.
![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/6182195b-38a7-44c3-81e8-8eb6095888a7)
3.
![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/4cef0eeb-b88a-42a4-8095-c72e079766b9)
4.
![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/97c2cb70-7259-400a-98d4-1dccda6250d9)

### 期望行为 | Expected Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/43739945-306d-4472-8f05-d8f82f3d36de)

### 复现方法 | Steps To Reproduce
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
tokenizer = AutoTokenizer.from_pretrained("path-to-your-model/Qwen-7B-Chat", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("path-to-your-model/Qwen-7B-Chat", device_map="cpu", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained("path-to-your-model/Qwen-7B-Chat", trust_remote_code=True)
response, history = model.chat(tokenizer, "你的模型参数是多少", history=["你好"])
print("=============================================")
print(response)
print("=============================================")
```

### 运行环境 | Environment

```Markdown
- OS: centos
- Python: 3.8.15
- Transformers: 4.31.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): None
```

### 备注 | Anything else?

期待上述问题的解决方法😀

**Comment by JianxinMa** [comment]
```
response, history = model.chat(tokenizer, "你的模型参数是多少", history=["你好"])
```

您好，这个history传错了，不能传history=["你好"] 。请参考 readme 或 cli_demo.py 脚本的用法。

**Comment by jiaigo** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/42903140/4d2c01d7-c8ec-4fee-9e05-ab6674665a25)

这是history为None的情况

**Comment by JianxinMa** [comment]
我看截图是用的 private/Qwen-7B-Chat，用官方的  Qwen/Qwen-7B-Chat 也会吗？会不会是误用 base 模型的 ckpt 作为 chat 模型了？我本地无法复现该 bad case。

**Comment by jiaigo** [comment]
是昨天在huggingface Qwen-7B-Chat下载的模型，当时看到的是一个大的15G的模型，现在看huggingface上的模型文件似乎与昨天有异，我先重新拉一下

**Comment by jiaigo** [comment]
已解决，将最新的huggingface Qwen-7B-Chat更新至本地。
