### ISSUE TITLE
💡 能否禁用flash_attn，放到配置里

### ISSUE THREAD

**Issue by huashiyiqike** [QwenLM/Qwen-7B#102]
### 起始日期 | Start Date

2023-8-7

### 摘要 | Summary

一直装不上这个包

### 基本示例 | Basic Example

ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

### 缺陷 | Drawbacks

modelscope的可以用，没装只会提示，但是不能选fp16,；huggingface的版本，必须装flash_attn

**Comment by bh4ffu** [comment]
确认一下transformers的版本，4.31.0版本不需要装flash_attn

**Comment by logicwong** [comment]
同上，旧版本的transformers会catch不不到ImportError，新版本修复了该问题https://github.com/huggingface/transformers/commit/89159651babbd4008a42ed08730d0f707ed91758

**Comment by yangapku** [comment]
@NeilRon 上面的意思是，如果transformers版本低于4.31.0，那么在不安装flash_attn的情况下，使用我们的代码会在import时候transformers里面报一个依赖错误哈（即使代码本身没有flash_attn也是可以正常跑的）。
如果更新到4.31.0，那不安装flash_attn的情况下，我们的代码也可以正常import并跑起来，但是效率还是会不如安装flash_attn的性能哈。您这边测试infer差异不大，可能还是序列长度较短，没有体现优势哈。

**Comment by yangapku** [comment]
@bh4ffu 我们的代码在transformers 4.31.0版本下，可以不使用flash_attn并跑起来inference哈，但是效率还是会不如安装flash_attn的性能。安装flash_attn是可选项，如果您的显卡支持flash_attn（支持的卡型参见issue 103回复 https://github.com/QwenLM/Qwen-7B/issues/103#issuecomment-1667412231），建议您使用flash_attn获得更高的效率。

**Comment by josangmi** [comment]
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cpu", trust_remote_code=True, fp16=True).eval()
我初始化model 的时候设定了cpu 模式，fp16=true 还是会出现：
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

加上：model = model.float() 之后
就成了：
RuntimeError: x1 must be on CUDA

我现在用的服务器是之前老机器，CPU64U，内存256G，但是显卡只有4G，没办法用GPU 模式，现在用CPU 模式应该怎么修改呢？谢谢。

第二个就是flash_attn的编译，已经跑了快24小时了，还没完成。 这个是不是可以停掉了。
