### ISSUE TITLE
[BUG] FlashAttention安装成功但使用报错

### ISSUE THREAD

**Issue by ryanhe919** [QwenLM/Qwen-7B#103]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

在Linux上配置环境，在未安装FlashAttention的时候一切正常，按照教程安装FlashAttention没有报错，但运行模型推理的时候报错RuntimeError: Expected is_sm90 || is_sm8x || is_sm75 to be true, but got false. (Could this error message be improved? If so, please report an enhancement request to PyTorch.)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

transformers的版本是 Version: 4.31.0

**Comment by ryanhe919** [comment]
transformers的版本是 Version: 4.31.0

**Comment by Zplusdragon** [comment]
I have met the same problem. Have you solved it?

**Comment by ryanhe919** [comment]
> I have met the same problem. Have you solved it?

not yet

**Comment by logicwong** [comment]
@Zplusdragon @ryanhe919 Please check whether your GPU supports FlashAttention, only Turing (sm75), Ampere (sm80, 86, 89) and Hopper (sm90) are supported.

**Comment by ryanhe919** [comment]
> <img alt="image" width="972" src="https://user-images.githubusercontent.com/17445544/258742497-9f8c3a61-5f27-4ba0-ba77-b22141e6d697.png"> @Zplusdragon @ryanhe919 The GPU types of Turing, Ampere and Hopper frameworks.

thx a lot, im using v100 and look like it's not suitable for flashatt
