### ISSUE TITLE
[BUG] <title>输入大概1000个字，输出特别慢

### ISSUE THREAD

**Issue by Amy234543** [QwenLM/Qwen-7B#105]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 复现方法 | Steps To Reproduce

tokenizer = AutoTokenizer.from_pretrained("./QWEN", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("./QWEN", device_map="auto", trust_remote_code=True).eval()
model.generation_config = GenerationConfig.from_pretrained("./QWEN", trust_remote_code=True) 
prompt='''
已知信息：二、严重脓毒症和脓毒性休克诊断标准,严重脓毒症是脓毒症伴由其导致的器官功能障碍和/或组织灌注不足，下述任意一项：(1)脓毒症所致低血压；(2)乳酸大于正常值；(3)即使给予足够的液体复苏，尿量仍< 0.5 ml·kg–1·h–1至少2 h；(4)非肺炎所致的急性肺损伤且PaO2/FiO2< 250 mmHg；(5)肺炎所致急性肺损伤且PaO2/FiO2 < 200 mmHg；(6)血肌酐>176.8 μmol/L (2.0 mg/dl)；(7)胆红素> 34.2 μmol/L (2 mg/dl)；(8)PLT< 100 000 μl；(9)凝血障碍(国际标准化比值> 1.5)。****中国严重脓毒症/脓毒性休克治疗指南(2014)
诊断标准,一、脓毒症诊断标准,存在明确或可疑的感染，并具备下述某些临床特点：1．一般临床特征,(1)发热(体温> 38.3℃)；(2)低体温(体温< 36℃) ；(3)心率> 90次/min，或大于不同年龄正常值的两个标准差；(4)气促；(5)精神状态的改变；(6)明显水肿或液体正平衡(24 h超过20 ml/kg)；(7)高血糖症[血糖>7.7 mmol/L(140 mg/dl)]且无糖尿病史。2．炎症反应指标,(1)白细胞增多(WBC > 12 000/μl)；(2)白细胞减少(WBC < 4 000/μl)；(3)WBC正常但幼稚白细胞总数超过10%；(4)血浆C反应蛋白>正常两个标准差；(5)血浆降钙素原>正常两个标准差。3．血流动力学,低血压[收缩压<90 mmHg(1 mmHg＝0.133 kPa),平均动脉压(MAP)<70 mmHg或成人收缩压下降超过40 mmHg或低于年龄段正常值两个标准差]。4．器官功能障碍,(1)低氧血症[PaO2/吸氧浓度(FiO2)< 300 mmHg]；(2)急性少尿(即使给予足够的液体复苏，仍然尿量< 0.5 ml·kg–1·h–1且至少持续2 h以上)；(3)血肌酐> 44.2 μmol/L(0.5 mg/dl)；(4)凝血功能异常(国际标准化比值>1.5或APTT> 60 s)；(5)肠梗阻(肠鸣音消失)；(6)血小板减少(PLT< 100 000/μl)；(7)高胆红素血症[血浆TBil>70 μmol/L (4 mg/dl)]。5．组织灌注指标,(1)高乳酸血症(乳酸>1 mmol/L)；(2)毛细血管再灌注能力降低或瘀斑形成。****中国严重脓毒症/脓毒性休克治疗指南(2014)
根据上述已知信息，专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：脓毒症诊断标准
'''
def _clear_screen():
    if platform.system() == "Windows":
        os.system("cls")
    else:
        os.system("clear")
for response in model.chat(tokenizer, prompt, history=None, stream=True):
    _clear_screen()
    print(f"\nUser: {prompt}")
    print(f"\nQwen-7B: {response}")

response, history = model.chat(tokenizer, prompt,history=None)
print('response:\n', response)

### 运行环境 | Environment

```Markdown
- OS:Linux gpu-a100-19 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Python:3.10
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):  11.7
两个A100
```

**Comment by yangapku** [comment]
您好，我们更新了一下update_rotary_pos_emb_cache的逻辑哈，之前因为update_rotary_pos_emb_cache调用过于频繁，导致长序列生成时额外增加了大量计算量。现在我们优化了update_rotary_pos_emb_cache的调用次数哈，长序列的生成速度会加快很多了，请您用最新的代码再尝试一下~
