### ISSUE TITLE
TransformersAgent与流式API冲突

### ISSUE THREAD

**Issue by liaoweiguo** [QwenLM/Qwen-7B#109]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

当使用过model.chat(stream=True)以后，再通过agent执行命令，会报错

File "～/.local/lib/python3.8/site-packages/transformers_stream_generator/main.py", line 324, in generate
    and generation_config.do_stream is True
AttributeError: 'GenerationConfig' object has no attribute 'do_stream'

不用stream就可以

### 期望行为 | Expected Behavior

stream是必要的，想办法改一下
<img width="348" alt="截屏2023-08-07 21 48 24" src="https://github.com/QwenLM/Qwen-7B/assets/22187224/1df93e5a-47f0-41b8-aad5-a71e8f00aa04">

### 运行环境 | Environment

```Markdown
- OS: Ubuntu2004
- Python: 3.8
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
12.2
```

**Comment by liaoweiguo** [comment]
实际上就是chat(stream=True)以后再chat(stream=False)失败，跟另外一个issue是同一个问题

**Comment by huajianmao** [comment]
#100

**Comment by fyabc** [comment]
@liaoweiguo 您好，该问题已经在最新的HuggingFace repo中修复，您可以更新到最新版本，然后重新尝试一下
在调用时，请将model.chat(..., stream=True)调用替换为model.chat_stream(...)，前者已废弃

更多信息可以参考 #100

**Comment by JianxinMa** [comment]
我删掉了之前的comments，因为我之前理解有误。我理解下，对 agent 的输出并没有stream的需求。仅仅只是因为用过stream后，没有办法调用agent吗？那可以尝试重新执行 from_pretrained 拉最新代码再试试~
