### ISSUE TITLE
'QWenLMHeadModel' object has no attribute 'chat_stream'

### ISSUE THREAD

**Issue by Lufffya** [QwenLM/Qwen-7B#119]
![image](https://github.com/QwenLM/Qwen-7B/assets/49063302/de3b3e6f-f5dc-4438-ba8f-60f29af08450)

**Comment by JianxinMa** [comment]
您好，应该是代码版本问题。请重新拉取 huggingface 上的代码，比如重新执行下 from_pretrained("Qwen/Qwen-7B-Chat")

**Comment by LittleXu1998** [comment]
> 您好，应该是代码版本问题。请重新拉取 huggingface 上的代码，比如重新执行下 from_pretrained("Qwen/Qwen-7B-Chat")

是huggingface上模型文件里的问题还是GitHub上项目文件里的问题

**Comment by JianxinMa** [comment]
> > 您好，应该是代码版本问题。请重新拉取 huggingface 上的代码，比如重新执行下 from_pretrained("Qwen/Qwen-7B-Chat")
> 
> 是huggingface上模型文件里的问题还是GitHub上项目文件里的问题

hugginface上的，https://huggingface.co/Qwen/Qwen-7B-Chat/tree/main 这里面的代码我们也会经常更新的，通常联网重新执行下 from_pretrained("Qwen/Qwen-7B-Chat") 就会拉取最新的。

**Comment by LittleXu1998** [comment]
好的好的



发自我的iPhone


------------------ Original ------------------
From: Jianxin Ma ***@***.***&gt;
Date: Tue,Aug 8,2023 4:12 PM
To: QwenLM/Qwen-7B ***@***.***&gt;
Cc: LittleXu1998 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [QwenLM/Qwen-7B] 'QWenLMHeadModel' object has no attribute'chat_stream' (Issue #119)





   
您好，应该是代码版本问题。请重新拉取 huggingface 上的代码，比如重新执行下 from_pretrained("Qwen/Qwen-7B-Chat")
  
是huggingface上模型文件里的问题还是GitHub上项目文件里的问题
  
hugginface上的，https://huggingface.co/Qwen/Qwen-7B-Chat/tree/main 这里面的代码我们也会经常更新的，通常联网重新执行下 from_pretrained("Qwen/Qwen-7B-Chat") 就会拉取最新的。

**Comment by aleimu** [comment]
解决了吗? 可是我看当前 https://huggingface.co/Qwen/Qwen-7B/blob/main/modeling_qwen.py 文件中还是没有stream_chat函数啊

**Comment by LittleXu1998** [comment]
我解决了





发自我的iPhone


------------------ Original ------------------
From: aleimu ***@***.***&gt;
Date: Thu,Aug 10,2023 3:26 PM
To: QwenLM/Qwen-7B ***@***.***&gt;
Cc: LittleXu1998 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [QwenLM/Qwen-7B] 'QWenLMHeadModel' object has no attribute'chat_stream' (Issue #119)





 
解决了吗? 可是我看当前 https://huggingface.co/Qwen/Qwen-7B/blob/main/modeling_qwen.py 文件中还是没有stream_chat函数啊

**Comment by ArtificialZeng** [comment]
response, _ = model.chat_stream(tokenizer, query, history=history)
ValueError: too many values to unpack (expected 2)

**Comment by LOGIC-10** [comment]
@JianxinMa 您分享的网页404了，找不到信息。
