### ISSUE TITLE
FlashAttention是必须要安装的吗？

### ISSUE THREAD

**Issue by DirtyKnightForVi** [QwenLM/Qwen-7B#12]
如题

**Comment by logicwong** [comment]
不是必须的。但推荐安装，可以节省显存和提升推理速度

**Comment by DirtyKnightForVi** [comment]
> 

但是加载模型的时候报错：ImportError, were not found in your enviroment: flash_attn

**Comment by DirtyKnightForVi** [comment]
> 不是必须的。但推荐安装，可以节省显存和提升推理速度

但是按照README里加载model的代码，这一行报错: This modeling file requires the following packages that were not found in your environment: flash_atten.

检查了一下，这是在huggingface模型中带了一个modeling_qwen.py有使用到。

**Comment by logicwong** [comment]
> > 不是必须的。但推荐安装，可以节省显存和提升推理速度
> 
> 但是按照README里加载model的代码，这一行报错: This modeling file requires the following packages that were not found in your environment: flash_atten.
> 
> 检查了一下，这是在huggingface模型中带了一个modeling_qwen.py有使用到。

可以把运行代码和完整报错贴一下吗？flash_atten这个名字也很奇怪，要报错的话应该也得报flash_attn才对吧。

**Comment by DirtyKnightForVi** [comment]
> > > 不是必须的。但推荐安装，可以节省显存和提升推理速度
> > 
> > 
> > 但是按照README里加载model的代码，这一行报错: This modeling file requires the following packages that were not found in your environment: flash_atten.
> > 检查了一下，这是在huggingface模型中带了一个modeling_qwen.py有使用到。
> 
> 可以把运行代码和完整报错贴一下吗？flash_atten这个名字也很奇怪，要报错的话应该也得报flash_attn才对吧。

这个问题我安装正确的flash-attn之后解决掉了。

**Comment by logicwong** [comment]
> > > > 不是必须的。但推荐安装，可以节省显存和提升推理速度
> > > 
> > > 
> > > 但是按照README里加载model的代码，这一行报错: This modeling file requires the following packages that were not found in your environment: flash_atten.
> > > 检查了一下，这是在huggingface模型中带了一个modeling_qwen.py有使用到。
> > 
> > 
> > 可以把运行代码和完整报错贴一下吗？flash_atten这个名字也很奇怪，要报错的话应该也得报flash_attn才对吧。
> 
> 这个问题我安装正确的flash-attn之后解决掉了。

之前这个问题是transformers老版本的问题，用最新的transformers 4.31.0可以fix掉，不用flash-attn也可以正常跑。

**Comment by logicwong** [comment]
> 可能v100用户是被上帝遗弃的

刚刚更新了config.json，你可以手动打开fp16精度加载模型：

```python
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="auto", trust_remote_code=True, fp16=True).eval()
```

**Comment by qihangf** [comment]
![1691119295700](https://github.com/QwenLM/Qwen-7B/assets/131108176/3a875dbe-1489-4a2e-a1e9-8b0d3414621f)
我在这步卡了两个小时正常吗，transformers4.31.0，torch2.0.1+cu117，显卡v100

**Comment by TuDaCheng** [comment]
我使用Python3.8/3.10安装这个flash-attention都装不上 报错  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects，有遇到过这个问题的小伙伴吗

**Comment by FrankMinions** [comment]
> > > > > 不是必须的。但推荐安装，可以节省显存和提升推理速度
> > > > 
> > > > 
> > > > 但是按照README里加载model的代码，这一行报错： 此建模文件需要以下在您的环境中找不到的包：flash_atten。 检查了一下，这是在huggingface模型中带了一个modeling_qwen.py有使用到。
> > > 
> > > 
> > > 可以把运行代码和完整报错贴一下吗？flash_atten这个名字也很奇怪，要报错的话应该也得报flash_attn才对吧。
> > 
> > 
> > 这个问题我安装正确的flash-attn之后解决掉了。
> 
> 之前这个问题是transformers老版本的问题，用最新的transformers 4.31.0可以fix掉，不用flash-attn也可以正常跑。

实测transformers换成4.31.0可以fix这个问题，不需要安装flash-attn

**Comment by txy6666yr** [comment]
> 
请问是怎么安装成功的呢？

**Comment by Michael-Steven** [comment]
只有Turing (sm75), Ampere (sm80, 86, 89) and Hopper (sm90) 架构的卡可以用Flash-attention
https://github.com/Dao-AILab/flash-attention/issues/292#issuecomment-1614741373

**Comment by txy6666yr** [comment]
> 

怪不得，谢谢大佬

**Comment by yangtianyu92** [comment]
> 只有Turing (sm75), Ampere (sm80, 86, 89) and Hopper (sm90) 架构的卡可以用Flash-attention [Dao-AILab/flash-attention#292 (comment)](https://github.com/Dao-AILab/flash-attention/issues/292#issuecomment-1614741373)

吐了，V100用户不是人是吧

**Comment by Jaren1907** [comment]
请教下，V100运行qwen-72B，config.json里面设置的fp16为True时，会报错`RuntimeError: FlashAttention only supports Ampere GPUs or newer.`
仅在将fp32设置为True时才能正确运行，但是使用fp32推理速度巨慢， 输入输出均在20tokens左右，耗时达到了惊人的20分钟；

1. 是否可以在V100使用fp16模式，应该如何配置及修改？
2. 推理过程中发现仅有第一张卡进行了运算，是否可以使用多卡推理进行加速，需要如何配置及修改？
