### ISSUE TITLE
CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Lufffya** [QwenLM/Qwen-7B#120]
![image](https://github.com/QwenLM/Qwen-7B/assets/49063302/e2317b00-9e97-4e49-852f-fc279c2fd385)

**Comment by jxst539246** [comment]
您好，可以补充下运行环境和加载模型使用的精度么，这个错误大概率是超显存导致的
