### ISSUE TITLE
[BUG] 运行FastChat fastchat.serve.vllm_worker报错

### ISSUE THREAD

**Issue by exceedzhang** [QwenLM/Qwen-7B#123]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

推理过程中出现decode错误，由于Qwen-7B-Chat/tokenization_qwen.py", line 228, in _decode 引起
<img width="1437" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/4583537/19d38bb0-4be8-4874-acf8-6332eeeefab5">

运行在vllm.entrypoints.api_server 正常工作
<img width="1438" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/4583537/c1bc7385-c296-407a-90f5-f5b4a12aaa4c">

**Comment by jklj077** [comment]
您好，根据报错信息，该问题是由于fastchat.serve.vllm_worker给tokenzier.decode传入了None。

具体而言，这[部分代码](https://github.com/lm-sys/FastChat/blob/6f188ab771f339d18e660dc0e1384fdb3d724790/fastchat/serve/vllm_worker.py#L71-L72)依赖传入模型特异的stop_token_ids。但似乎并未传入[这里](https://github.com/lm-sys/FastChat/blob/6f188ab771f339d18e660dc0e1384fdb3d724790/fastchat/conversation.py#L912-L916)适配的Qwen-7B-Chat的stop_token_ids。

或许，您可以通过为generate_stream的params参数配置正确的stop_token_ids来解决该问题。但由于我们无法强制其它库的执行逻辑，且相关代码均在fastchat库中，如有更多问题，建议您首先联系fastchat的维护者。感谢支持！

**Comment by exceedzhang** [comment]
@jklj077 谢谢，我已经跑通了！在请求中增加参数stop_token_ids=[151643,151644,151645,]来解决，目前已正常运行！

**Comment by exceedzhang** [comment]
<img width="1512" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/4583537/c40cefc0-1458-4a59-9fa6-409dfa9c634a">

**Comment by fushun1990** [comment]
我和你遇到相同的问题了，请问你是怎么解决了的了，我试用过。

**Comment by fushun1990** [comment]
我和你遇到相同的问题了，请问你是怎么解决了的了，我试用过。
`python -m vllm.entrypoints.openai.api_server --model /home/wxwl_server/project/model/Qwen/Qwen-7B-Chat --trust-remote-code --host [0.0.0.0](http://0.0.0.0/) --port 8200`
调用代码
` import openai
        openai.api_base = thread_worker_addr + "/v1"
        openai.api_key = "none"
        messages = [{"role": "user", "content": "Hello!What is your name?"}]
        res = openai.ChatCompletion.create(model=args.model_name, messages=messages, stream=True)
        for chunk in res:
            content = chunk["choices"][0]["delta"].get("content", "")
            print(content, end="", flush=True)
        print()`
在调用的时候，就一直不返回，

我也用
`python3 -u -m fastchat.serve.vllm_worker --model-path /home/wxwl_server/project/model/Qwen/Qwen-7B-Chat --trust-remote-code`
调用的，也是返回一样的错误。vllm 的版本是0.1.3 fastChat最新代码 main分支。
