### ISSUE TITLE
一些简单的测试提问对比,  发现一些badcase. 放到这里你们参考下吧。

### ISSUE THREAD

**Issue by wysaid** [QwenLM/Qwen-7B#124]
用readme里面提到的最新参数， 测试了几个例子， 举一个 bad case吧， 就是让 通义千问 来给我出题， 它似乎无法理解。 也许是我提问的方式有问题， 但我用同样的方式问了几个别的AI， 都能很快给出题目， 而不是跟我绕弯子死磕：

![image](https://github.com/QwenLM/Qwen-7B/assets/1430725/d441dbd0-4d9f-4e13-9885-905ce9e9cf4b)
![image](https://github.com/QwenLM/Qwen-7B/assets/1430725/fd9af596-1c4e-4c2b-bd5c-3f60a9c37c37)
![image](https://github.com/QwenLM/Qwen-7B/assets/1430725/5f500b0e-4f86-4714-bb5a-2beb264c868b)

## 完整的对话：

- User: 请充当我的小学老师， 出几道题来考察我。
- Qwen: 当然可以！请问您需要哪个学科的题目？数学、语文、英语、物理、化学等？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

- User: 数学
- Qwen: 请问您需要哪个方向的数学题？代数、几何、数论、组合、概率论等？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

- User: 代数
- Qwen: 请问您需要哪个难度的代数题？初级、中级、高级？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

- User: 初级
- Qwen: 请问您需要哪个方向的初级代数题？一元一次方程、一元二次方程、不等式、函数等？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

- User: 一元一次方程
- Qwen: 请问您需要哪个难度的一元一次方程题？初级、中级、高级？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

- User: 初级
- Qwen: 请问您需要哪个方向的初级代数题？一元一次方程、一元二次方程、不等式、函数等？请告诉我您需要的题型和难度级别，我会尽力帮您出题。

---

之后开始循环往复.

别的 AI 就不举例了， 都能给出问题， 虽然不一定是我想要的问题， 但是不至于死磕。

**Comment by wysaid** [comment]
上面的对话是可复现的， 我试了 N 次， 都是这样的结果.

**Comment by wysaid** [comment]
可以在这里方便复现， 用的是截止目前issue时间最新的版本: <http://chat.boxiao.wang:60080/>

**Comment by wysaid** [comment]
补充： 测试了 chatglm2-6b， 没有这个问题

**Comment by JianxinMa** [comment]
我在 https://modelscope.cn/studios/qwen/Qwen-7B-Chat-Demo/summary 试了下，prompt 合适的可以直接出题目。

比如
```
USER's PROMPT:
请充当我的小学老师，出几道题考察我。直接出题目，不要问问题。

QWEN's RESPONSE:
1. 填空：数学课上，我们学习了_______的概念，它是用来表示物体_______的。

2. 选择题：下列哪种图形是轴对称图形？
A. 线段 B. 平行四边形 C. 等边三角形 D. 梯形

3. 判断题：如果两个角的和是90度，那么这两个角是同位角。
（ ）
```

**Comment by jxst539246** [comment]
> 上面的对话是可复现的， 我试了 N 次， 都是这样的结果.

因为我们默认是采样策略，并不应该出现重试N次都是同样结果，如果是使用流式输出接口构建的demo可以重新拉取一下最新代码，之前的版本random seed被其他库固定导致每次生成结果一致。

**Comment by JianxinMa** [comment]
我刚用开源版本的 model.chat 接口也试了下，只要要求模型 “直接出题目，不要问问题。”，都是能 work 的~

**Comment by wysaid** [comment]
了解， 倒不是非得让它出这个题目， 而是追问，按照ta给的选项一直追问， 一直都给不出想要的结果， 会陷入循环， 这个感觉不太好。如果能解决这个问题， 就不需要对发文做具体格式要求了
