### ISSUE TITLE
💡 [REQUEST] -NTK方法在SFT微调时可用吗？

### ISSUE THREAD

**Issue by xyfZzz** [QwenLM/Qwen-7B#126]
### 摘要 | Summary

NTK方法在SFT微调时可用吗？能否在微调时就扩展长度？

### 基本示例 | Basic Example

NTK方法在SFT微调时可用吗？能否在微调时就扩展长度？

### 缺陷 | Drawbacks

NTK方法在SFT微调时可用吗？能否在微调时就扩展长度？

**Comment by fengcai24** [comment]
请问题主是用哪个训练框架代码呢

**Comment by xyfZzz** [comment]
> 

我用的是LLaMA-Efficient-Tuning

**Comment by xyfZzz** [comment]
> 请问题主是用哪个训练框架代码呢


我用的是LLaMA-Efficient-Tuning

**Comment by logicwong** [comment]
@xyfZzz 据我所知，通过SFT微调扩展上下文长度时，线性插值似乎比NTK更好，但具体比较我还没尝试过。
