### ISSUE TITLE
[BUG] 更新 requirements.txt

### ISSUE THREAD

**Issue by samchugit** [QwenLM/Qwen-7B#127]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

请更新 requirements.txt。web demo 依赖的 gradio 以及 mdtex2html 并没有更新进来。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/0567c474-897c-4f30-b6f5-09f18a9fe8c8)
To avoid problems, we just put the installation of both packages right here as they are not related to other usages.

**Comment by samchugit** [comment]
Thanks for the rapid response. I'll close this issue since the problem is solved.
