### ISSUE TITLE
[BUG] User: 写一个励志的剧本 'AsyncRequest' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by Jacobs12** [QwenLM/Qwen-7B#129]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

输出一段长文本web_demo.py会报错

### 期望行为 | Expected Behavior

输出一段长文本web_demo.py会报错

### 复现方法 | Steps To Reproduce

User: 写一个励志的剧本 

### 运行环境 | Environment

```Markdown
- OS:ubuntu
- Python:3.10.6
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.0
```

### 备注 | Anything else?

无

**Comment by Jacobs12** [comment]
魔搭社区上的demo在输出一篇长文本时也会报错error

**Comment by Jacobs12** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/12640927/561dfc85-3747-43fc-8586-ed23af208826)
《写一篇作文，不少于1000字》，这样出现错误的几率会很大

**Comment by Jacobs12** [comment]
在cli_demo.py可以生成长文本是没有问题的，这个问题只出现在web_demo.py

**Comment by Jacobs12** [comment]
请注意文本框中间位置的Error字样，这段文本是没有完全输出的，中间报错了

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/deb44cc5-7653-46a1-ae7d-321a553c5185)
我似乎还不会崩掉。你当前再试还有这个问题？

**Comment by JustinLin610** [comment]
没写完我写继续，出现一次connection的error，再重试也ok。好像不太好复现

**Comment by Jacobs12** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/12640927/4fd440c0-2963-43ca-a13b-5dcac684794c)
没写完停住的时候，服务器的控制台就出现AsyncRequest' object has no attribute '_json_response_data' 这个错误了，只不过在gradio里面没有提示error，我以为是我配置的环境的问题，然后在魔搭上试了一下同样也有这个问题，这个问题很好复现，没写完的时候就是已经报错了

**Comment by Jacobs12** [comment]
在cli_demo.py输出一篇1000字的作文的时候是能够完整输出的，没有出现写不完的情况，这里出现写不完的情况是因为报错了导致文本输出停止了

**Comment by JustinLin610** [comment]
有些奇怪了，不管是写作文这个还是剧本，都是在modelscope demo上尝试多次都没遇到问题
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/291a348b-d469-41b4-bb4f-e53d239b9dc5)

**Comment by Jacobs12** [comment]
约束一下字数，写上“不少于1000字”，输出大约一屏半的时候就会突然停住了，这个时候你再点发送，就会报error了，这个bug我这边测试的是100%必现，请注意：！！！输出停止时并不是正常停止的，而是报错停止的，文本输出并没有完成！！！但是浏览器没有错误提示，我们会误以为输出完成了，此时点“发送”就会出现报错了

**Comment by Jacobs12** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/12640927/d87fc3f0-73da-40bb-a522-382e28bce231)
输入的提示词为《写一篇作文，不少于1000字》

**Comment by JustinLin610** [comment]
在modelscope那边查了下，前面的中断就是正常生成然后没生成完结束了。接着点击发送，是因为这个demo不支持空的输入，然后报错了。先暂时不要发送空的输入，断了你可以写个 继续

**Comment by Jacobs12** [comment]
原来是这样，那魔搭应该是正常的，跟我本地服务器部署的不是同一个问题，可能是我环境的问题，我再研究研究，我服务器上就输出几十个字之后就报 'AsyncRequest' object has no attribute '_json_response_data'

**Comment by RookieDay** [comment]
mac 上运行没有问题，win 上运行会报这样的错误
