### ISSUE TITLE
直接用提供的transformers例子跑不起来

### ISSUE THREAD

**Issue by maiqingqiang** [QwenLM/Qwen-7B#13]
用这个例子跑不起来[transformers](https://github.com/QwenLM/Qwen-7B#-transformers)

gpu感觉不用上，最后ram占满崩溃。。。

![image](https://github.com/QwenLM/Qwen-7B/assets/1825679/72442451-f7eb-4b6d-9d27-85cd32d49715)

**Comment by DirtyKnightForVi** [comment]
官方demo运行时报错，就是卡在flash_attn那里。似乎没能try成功

**Comment by logicwong** [comment]
@maiqingqiang 感觉是跟#15 一样的问题。你可以试试最新代码，手动打开fp16精度加载模型：

```python
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="auto", trust_remote_code=True, fp16=True).eval()
```

**Comment by TuDaCheng** [comment]
使用量化的模型加载了 报错RuntimeError: value cannot be converted to type at::Half without overflow

**Comment by JustinLin610** [comment]
> 使用量化的模型加载了 报错RuntimeError: value cannot be converted to type at::Half without overflow

最新的代码测试依然不行吗？提供一下代码和报错的截图？我这边测试nf4和int8都没发现问题。

**Comment by chelovek21** [comment]
官方HF示例，int8量化加载，报这个错误
response, history = model.chat(tokenizer, "你好", history=None)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 905, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 951, in generate
    return super().generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2655, in sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen_generation_utils.py", line 349, in __call__
    scores[i, self.eos_token_id] = float(2**30)
RuntimeError: value cannot be converted to type at::Half without overflow

**Comment by JustinLin610** [comment]
> 官方HF示例，int8量化加载，报这个错误 response, history = model.chat(tokenizer, "你好", history=None) File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 905, in chat outputs = self.generate( File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 951, in generate return super().generate( File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2655, in sample next_token_scores = logits_processor(input_ids, next_token_logits) File "/usr/local/lib/python3.8/dist-packages/transformers/generation/logits_process.py", line 97, in call scores = processor(input_ids, scores) File "/root/.cache/huggingface/modules/transformers_modules/qwen_generation_utils.py", line 349, in call scores[i, self.eos_token_id] = float(2**30) RuntimeError: value cannot be converted to type at::Half without overflow

更新一下最新代码，Auto的from pretrained应该可以。qwen_generation_utils第349行，已经将其改为2**15，不会溢出
