### ISSUE TITLE
[BUG] <device_map="cpu"，不生效>

### ISSUE THREAD

**Issue by josangmi** [QwenLM/Qwen-7B#131]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cpu", trust_remote_code=True, fp16=True).eval()
我初始化model 的时候设定了cpu 模式，fp16=true 还是会出现：
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

加上：model = model.float() 之后
就成了：
RuntimeError: x1 must be on CUDA

我现在用的服务器是之前老机器，CPU64U，内存256G，但是显卡只有4G，没办法用GPU 模式，现在用CPU 模式应该怎么修改呢？谢谢。

第二个就是flash_attn的编译，已经跑了快24小时了，还没完成。 这个是不是可以停掉了。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.11
- Transformers:4.31.0
- PyTorch:2.0.1+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

CPU 模式

**Comment by JustinLin610** [comment]
按README的示例里面cpu的示例写就行，不要加上fp16=True

flash_attn不安装也可以跑的

**Comment by JustinLin610** [comment]
cpu支持Half有问题的，不要打开fp16

**Comment by josangmi** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/46701832/b91abf7c-6873-4b5f-b215-8f39421e3a4c)
已经去掉了，难道需要fp16=False ?

**Comment by JustinLin610** [comment]
或者重启环境试一次吧，这个报错还是因为Half
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/aad5a887-535c-4ee0-aa4d-32dfaf12eaa1)

如图所示可以正常load进cpu做inference的

**Comment by jxst539246** [comment]
@josangmi 
可以指定fp32=True试下

**Comment by josangmi** [comment]
> 或者重启环境试一次吧，这个报错还是因为Half ![image](https://user-images.githubusercontent.com/27664428/259389496-aad5a887-535c-4ee0-aa4d-32dfaf12eaa1.png)
> 
> 如图所示可以正常load进cpu做inference的

我们网络控制比较严格，所以我是下载模型到本地加载的，和这个有关系吗？

**Comment by josangmi** [comment]
> @josangmi 可以指定fp32=True试下

![image](https://github.com/QwenLM/Qwen-7B/assets/46701832/dda2b6ca-144e-49e4-a6f9-b21362082e05)
![image](https://github.com/QwenLM/Qwen-7B/assets/46701832/2459cf82-746d-4e14-8f21-59d6bace7662)
还是一样，好奇怪。

**Comment by josangmi** [comment]
果然路径修改为“Qwen/Qwen-7B-Chat”
![image](https://github.com/QwenLM/Qwen-7B/assets/46701832/1894dea8-7fc9-4f51-b0a6-e5725289a659)
就好了，等我再下载一下最新版看看。

**Comment by josangmi** [comment]
重新更新模型之后就好了。 
from huggingface_hub import snapshot_download
snapshot_download(repo_id="Qwen/Qwen-7B-Chat")
用的上面的方式下载的。
