### ISSUE TITLE
[BUG] 千问模型对prompt中出现 格式化输出markdown json 的表述时，返回的结果总是包含 ```json

### ISSUE THREAD

**Issue by zhengxiang5965** [QwenLM/Qwen-7B#135]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

**以langchain的conversation_chat agent的prompt为例**

When responding to me, please output a response in one of two formats:

\*\*Option 1:\*\*
Use this if you want the human to use a tool.
Markdown code snippet formatted in the following schema:

\`\`\`json
{{{{
    "action": string, \\ The action to take. Must be one of {tool_names}
    "action_input": string \\ The input to the action
}}}}
\`\`\`

\*\*Option #2:\*\*
Use this if you want to respond directly to the human. Markdown code snippet formatted in the following schema:

\`\`\`json
{{{{
    "action": "Final Answer",
    "action_input": string \\ You should put what you want to return to use here
}}}}
\`\`\`

**qwen总是格式化包含\`\`\`json 的结果**

2023-08-09 02:02:33 [ERROR]: [server]: Error: Failed to parse. Text: "\`\`\`json
{{
    "action": "Final Answer",
    "action_input": "I am a large language model trained by OpenAI. I am called QianWen."
}}
\`\`\`". Error: SyntaxError: Unexpected token { in JSON at position 1
Error: Failed to parse. Text: "```json
{{
    "action": "Final Answer",
    "action_input": "I am a large language model trained by OpenAI. I am called QianWen."
}}
\`\`\`". Error: SyntaxError: Unexpected token { in JSON at position 1
    at ChatConversationalAgentOutputParser.parse (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/agents/chat_convo/outputParser.cjs:48:19)
    at OutputFixingParser.parse (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/output_parsers/fix.cjs:55:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/agents/executor.cjs:88:28)
    at async AgentExecutor.call (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:90:28)
    at async ConversationalAgent_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/ConversationalAgent/ConversationalAgent.js:90:24)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:866:23)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:559:13

### 期望行为 | Expected Behavior

**返回格式化的json，不包括 ```json**

### 复现方法 | Steps To Reproduce

**使用以下prompt，让qwen去回答：**

Markdown code snippet formatted in the following schema:

\`\`\`json
{{{{
    "action": string, \\ The action to take. Must be one of {tool_names}
    "action_input": string \\ The input to the action
}}}}
\`\`\`

全文：

When responding to me, please output a response in one of two formats:

\*\*Option 1:\*\*
Use this if you want the human to use a tool.
Markdown code snippet formatted in the following schema:

\`\`\`json
{{{{
    "action": string, \\ The action to take. Must be one of {tool_names}
    "action_input": string \\ The input to the action
}}}}
\`\`\`

\*\*Option #2:\*\*
Use this if you want to respond directly to the human. Markdown code snippet formatted in the following schema:

\`\`\`json
{{{{
    "action": "Final Answer",
    "action_input": string \\ You should put what you want to return to use here
}}}}
\`\`\`

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by zhengxiang5965** [comment]
@yangapku @JustinLin610

**Comment by JianxinMa** [comment]
千问没有训过这个格式~ 希望使用ReAct的话，建议用我们文档里的格式，表现会更稳定些：https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_prompt.md

如果您是想用 langchain 的话，我们建议只使用 langchain 的 tool 实现，这方面我们稍后会补充个演示文档。我们不建议用 langchain 的 prompt 组装逻辑，其内部实现非常复杂而且容易出错。

回到您的关于 ```json 的问题，这个输出严格来讲不算有问题？因为提供的 in-context examples 就带了 ```json 。实在希望使用此格式的话，可能需要额外改下代码、处理掉这个 ```json 。

**Comment by JianxinMa** [comment]
您好，方便提供下您跑 langchain 的代码吗？我们看了 langchain 的代码，似乎是有对输出的 ` ```json ` 进行处理的。我们想复现下，看下是什么原因。目前只看 qwen 模型输出的话，看不到太大问题。
