### ISSUE TITLE
关于 WMT22(en-zh) 测评结果的问题

### ISSUE THREAD

**Issue by gpengzhi** [QwenLM/Qwen-7B#137]
Great work！

Qwen-7B 所取得的 30.6 是 zh -> en 和 en -> zh 的平均 SacreBLEU 吗？
具体用的 WMT22 哪一个测试集？可以告诉我对应的下载链接吗？

谢谢！

**Comment by Losin** [comment]
30.6是en-zh的值，zh-en是24.3，具体的值可以参考我们的tech memo  https://github.com/QwenLM/Qwen-7B/blob/main/tech_memo.md

数据是通过sacrebleu.get_langpairs_for_testset("wmt22")下载的，基于lm-eval-harness评测，inference方式是greedy， 5-shot
