### ISSUE TITLE
[BUG] < AttributeError: module 'os' has no attribute 'statvfs'>

### ISSUE THREAD

**Issue by Song367** [QwenLM/Qwen-7B#138]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

运行web_demo.py 报错  AttributeError: module 'os' has no attribute 'statvfs'

### 期望行为 | Expected Behavior

AttributeError: module 'os' has no attribute 'statvfs'

### 复现方法 | Steps To Reproduce

1. cuda 11.7
2. python 3.10
3. pytorch 2.0.1
4. gradio 3.37.0
5. windows

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

AttributeError: module 'os' has no attribute 'statvfs'

**Comment by fyabc** [comment]
Hi @Song367 ，can you provide more detailed information about this error?

1. OS version
2. `aiofiles` package version (`pip list`)

According to AUTOMATIC1111/stable-diffusion-webui#12433, this may be a bug in `aiofiles` (`gradio` depends on it).
You can try to update this package then retry:

```bash
pip install aiofiles==23.2.1
```
