### ISSUE TITLE
[BUG] tokenizer的_convert_token_to_id对special token处理错误，与convert_tokens_to_ids不一致

### ISSUE THREAD

**Issue by LiuShixing** [QwenLM/Qwen-7B#141]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/14970396/6d665309-f0ce-466c-ad88-e1c22692fdc1)

### 期望行为 | Expected Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/14970396/f42025f0-174d-406e-9979-6760516ece8a)

### 复现方法 | Steps To Reproduce

复现代码：
```python
import json
from transformers import AutoTokenizer, AutoModelForCausalLM
from collections import OrderedDict
model_path = "/apdcephfs_cq3/share_1474452/shixingliu/project/pretrained_models/Qwen/Qwen-7B"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
special_tokens = OrderedDict()
_ids = tokenizer.convert_tokens_to_ids(tokenizer.all_special_tokens)
for t, id in zip(tokenizer.all_special_tokens, _ids):
    special_tokens[t] = id
print(special_tokens)

special_tokens = OrderedDict()
for t in tokenizer.all_special_tokens:
    special_tokens[t] = tokenizer._convert_token_to_id(t)
print(f"错误结果：")
print(special_tokens)
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
您好，我们前几日重构过tokenizer的代码，目前看您使用的仍是之前版本的tokenizer，请先尝试更新代码试试。

如还有其它问题请反馈给我们。即便如此，从您的代码维护角度考虑，_convert_token_to_id根据命名是**私有**方法，请直接使用convert_tokens_to_ids。

**Comment by LiuShixing** [comment]
好的，感谢
