### ISSUE TITLE
[HELP] 大家有没有推理加速的方案，目前看qwen推理速度不理想

### ISSUE THREAD

**Issue by bh4ffu** [QwenLM/Qwen-7B#152]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

qwen推理速度不理想

### 期望行为 | Expected Behavior

提高推理速度

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by txy6666yr** [comment]
我在T4上量化推理，真的卡。

**Comment by JustinLin610** [comment]
提供一下具体的复现方法，以及具体的机器配置吧

**Comment by xusenlinzy** [comment]
[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm) 针对qwen模型的输入和输出做了一些 [vllm](https://github.com/vllm-project/vllm) 的适配，大家可以测试一下效果怎么样。使用方式见 https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md

**Comment by Sanster** [comment]
vllm main 分支已经支持 QWen-7b 的推理 https://github.com/vllm-project/vllm/pull/685

**Comment by NiHaoUCAS** [comment]
我在v100上测试，qwen7b和baichuan13b的速度相当，两个模型都没有用flash-attention。

**Comment by bh4ffu** [comment]
vllm用起来了，目前效果还可以，持续关注，感谢提供资料！

**Comment by yliuhb** [comment]
> vllm用起来了，目前效果还可以，持续关注，感谢提供资料！

请问有vllm， 最大长度可以是8k吗

**Comment by cgq0816** [comment]
> vllm用起来了，目前效果还可以，持续关注，感谢提供资料！

请问能提供一下测试代码吗？我这里测试发现效果并不好

**Comment by WangJianQ-cmd** [comment]
> 我在v100上测试，qwen7b和baichuan13b的速度相当，两个模型都没有用flash-attention。

您好，请问您使用的是什么推理方式？
对比的数据，是进行多个并发比对还是一个并发对比。对比的token大概多长
