### ISSUE TITLE
[BUG] <title>安装官方给的flash-attention装不上什么原因？

### ISSUE THREAD

**Issue by TuDaCheng** [QwenLM/Qwen-7B#156]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

我的显卡是V100 32G的  不装flash-attention部署推理Qwen-7B也没有问题 但是想加速一下

**Comment by logicwong** [comment]
@TuDaCheng V100不支持flash-attention。。在输入长度较短，输出长度较长时，flash-attention对推理并没有明显优势，具体可参见 #49
