### ISSUE TITLE
[BUG] 关于使用7B pretrain模型做finetune时的special token设置

### ISSUE THREAD

**Issue by liu6381810** [QwenLM/Qwen-7B#158]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

hi您好，我想使用Qwen-7B做多模态训练(会将Qwen-7B freeze)，我会有一个image_embeds和一些title_text，以及需要生成的tag_text，所以我希望将这些输入(特别是文本输入)concat的时候尽量和Qwen-7B在训练时的设置尽量保持一致。目前看到tokenizer只有一个endoftext的special token，想问下在Qwen-7B 训练阶段文本输入经过tokenizer后只有文本本身的input_ids和最后的endoftext对应的id吗？如果是的话我只需要将title_text和tag_text concat经过tokenizer最后再对label做一些处理就可以对齐？
期待您的回答，麻烦了～谢谢！

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
感谢支持！预训练中确实只使用了`<|endoftext|>`这一个特殊token。同时，我们的多模态模型也已经开源了，https://github.com/QwenLM/Qwen-VL，欢迎试用，huggingface中相关代码可能也可以参考。
