### ISSUE TITLE
[BUG] file `requirements_web_demo.txt` is missing

### ISSUE THREAD

**Issue by samchugit** [QwenLM/Qwen-7B#166]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

File `requirements_web_demo.txt` supporting for web ui dependency installing is missing, please add it.

### 期望行为 | Expected Behavior

Add `requirements_web_demo.txt` to make sure `pip install -r requirements_web_demo.txt` behaves normally.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
Thank you for pointing this out ❤️ ! I have added this file in the main branch. Please pull the latest commit and have a try!
