### ISSUE TITLE
[BUG] <title>module 'transformers_modules.tokenization_qwen' has no attribute 'QWenTokenizer'

### ISSUE THREAD

**Issue by getong95** [QwenLM/Qwen-7B#172]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行cli_demo.py遇到以下问题：

Traceback (most recent call last):
  File "/home/getong003/Qwen-7B/cli_demo.py", line 195, in <module>
    main()
  File "/home/getong003/Qwen-7B/cli_demo.py", line 103, in main
    model, tokenizer = _load_model_tokenizer(args)
  File "/home/getong003/Qwen-7B/cli_demo.py", line 41, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/getong003/anaconda3/envs/qwen_chat/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/home/getong003/anaconda3/envs/qwen_chat/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/getong003/anaconda3/envs/qwen_chat/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 165, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.tokenization_qwen' has no attribute 'QWenTokenizer'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
不太符合预期，你试下是不是拉代码有些问题或者不是拉最新代码？以及可以提供下复现方法

**Comment by getong95** [comment]
重新拉了代码ok啦

**Comment by AnYiz** [comment]
> 不太符合预期，你试下是不是拉代码有些问题或者不是拉最新代码？以及可以提供下复现方法

我在训练的时候也遇到了这个问题，重新拉取代码后不能解决
![bug](https://github.com/QwenLM/Qwen/assets/95127377/7f5cf6ff-6c13-4d04-b0a3-a2c50f586eca)

**Comment by basaltzhang** [comment]
> > 不太符合预期，你试下是不是拉代码有些问题或者不是拉最新代码？以及可以提供下复现方法
> 
> 我在训练的时候也遇到了这个问题，重新拉取代码后不能解决 ![bug](https://private-user-images.githubusercontent.com/95127377/305635766-7f5cf6ff-6c13-4d04-b0a3-a2c50f586eca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTA4NTgsIm5iZiI6MTcwOTI5MDU1OCwicGF0aCI6Ii85NTEyNzM3Ny8zMDU2MzU3NjYtN2Y1Y2Y2ZmYtNmMxMy00ZDA0LWIwYTMtYTJjNTBmNTg2ZWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3YTE5ZDExYjNlNTYzZDU1MTgyNWYxODAzN2YyZDc0MjRlZDBiOTA4NGJmNzBjMDE0YjUwMjRmYjA4NDM2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0m3xdxPHzqibnXr3oQ8n-4s34ebeSz8T4asZSWx25Jk)

run following command in the downloaded model directory `touch __init__.py `

**Comment by ypw-lbj** [comment]
同样的bug，如何解决？重新拉取什么代码？

**Comment by trotsky1997** [comment]
> 同样的bug，如何解决？重新拉取什么代码？

清空缓存目录里的remote代码缓存

**Comment by nxznm** [comment]
> > 同样的bug，如何解决？重新拉取什么代码？
> 
> 清空缓存目录里的remote代码缓存

请问这是什么原因呢？`AutoTokenizer.from_pretrained(tokenizer, trust_remote_code=True)`即使写明从本地路经加载tokenizer，也会优先从缓存目录里的remote代码读取？

**Comment by PineappleWill** [comment]
> > 同样的bug，如何解决？重新拉取什么代码？
> 
> 清空缓存目录里的remote代码缓存

请问是什么缓存目录？我有同样的bug
