### ISSUE TITLE
大家分享一下推理速度咯

### ISSUE THREAD

**Issue by bh4ffu** [QwenLM/Qwen-7B#173]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS: 20.04
- Python: 3.8
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.0

docker环境运行，宿主机：centos 7.9 内核版本：3.10.0-1160.88.1.el7.x86_64
```

### 备注 | Anything else?

显卡：V100显卡
输入：664个字符
输出：82个字符

平均耗时：2s

**Comment by Coder-nlper** [comment]
显卡：A10
输入：62
输出：20

速度：17.62 tokens/s

使用text-generation-webui进行部署

**Comment by yangapku** [comment]
请移步issue #175 讨论哈，两个issue基本是重复的，我这里就不同时open了 @Coder-nlper @bh4ffu
