### ISSUE TITLE
[BUG] 关于flash-attention在模型推演中使用的疑惑

### ISSUE THREAD

**Issue by sxueck** [QwenLM/Qwen-7B#176]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我的代码执行报错

```
Traceback (most recent call last):
  File "/home/sxueck/llm/Qwen-7B/test.py", line 25, in <module>
    AutoModelForCausalLM.from_pretrained(
  File "/home/sxueck/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "/home/sxueck/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: QWenLMHeadModel.__init__() got an unexpected keyword argument 'attention_type
```

### 期望行为 | Expected Behavior

我的疑惑是，flash-attention 似乎并没有支持 qwen-7b-chat 模型（可能我的理解有问题），模型加载的时候不支持 attention_type 并报错，但是如果我不指定的话会使用默认机制，我翻阅了项目的文档似乎并没有找到更详细的 flash-attention 参考，如果能有案例那再好不过了

### 复现方法 | Steps To Reproduce

我的代码：

> 其中我将模型的 attention mechanism 配置为了 `flash`，而不是 `nf4`

```python
import flash_attn
...

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='flash',
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    trust_remote_code=True)

model = (
    AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        quantization_config=quantization_config,
        trust_remote_code=True,
        bf16=True,
        attention_type="flash"
    ).eval())

model.generation_config = (
    GenerationConfig.from_pretrained(
        model_name, trust_remote_code=True, top_k=30000, repetition_penalty=1.3))
...
```

我的编译和调用过程（根据项目README进行）

```shell
$ git clone -b v1.0.8 https://github.com/Dao-AILab/flash-attention
$ cd flash-attention && pip install .
$ pip install csrc/layer_norm
$ pip install csrc/rotary
$ pip install ninja
$ python3 setup.py build_ext --inplace
```

### 运行环境 | Environment

```Markdown
- OS: WSL2 Ubuntu
- Python: 3.10.12
- Transformers: 4.31.0
- PyTorch: 2.0.1+cu117
- CUDA 11.7
- 配置：RTX3080(10G显存)+i913900K
```

**Comment by 77h2l** [comment]
pip install csrc/layer_norm  在执行这一步骤的时候是不是会卡住非常长的时间
flash_attn明明已经装好了，怎么还非得要单独安装这些kernel

**Comment by yangapku** [comment]
@77h2l 您好，flash_attn里面的一些fused算子（比如layer_norm）默认安装时，是不进行编译和安装的（默认安装的主要是flash_attn_unpadded_func，这个是flash_attn最核心的attention加速算子）。但是我们这里是可以支持并获得更高效率的，所以您可以按照安装command单独编译安装下（可选），编译确实需要花一些时间，不过也只是一次性的。

**Comment by 77h2l** [comment]
@yangapku  感谢回复哈，Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz  128核配置，在执行pip install csrc/layer_norm 卡了24小时还没执行完，是不是不太正常，htop显示cicc进程还在跑，ninja编译器这些都已经安装，就是一直卡在这一步无反应。。

**Comment by 77h2l** [comment]
实测 https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch 用torch的nv镜像，编译过程是正常的，否则在这一步会失去响应，长时间卡住不结束。

**Comment by 77h2l** [comment]
@yangapku  另外有个问题想请教一下，flash_attn的enable 在Qwen的推理环节是怎么生效的，这部分代码似乎readme里没有看到说明。

**Comment by AnitaSherry** [comment]
> @yangapku 感谢回复哈，Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz 128核配置，在执行pip install csrc/layer_norm 卡了24小时还没执行完，是不是不太正常，htop显示cicc进程还在跑，ninja编译器这些都已经安装，就是一直卡在这一步无反应。。

csrc/layer_norm编译成功了吗？
