### ISSUE TITLE
Qwen 7B base 能否web demo 多轮对话输出？

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen-7B#178]
将web_demo 改为base版本后加载，发现不能chat，官方给的推理代码是generate方法，
请问base版本是否可以提供web_demo的形式？
或者，有没有大佬指点下，base版本如何流式输出、多轮对话。
```
  File "/root/.cache/huggingface/modules/transformers_modules/lora-8-12-alpaca_gpt4_zh_20k/modeling_qwen.py", line 1042, in chat_stream
    assert self.generation_config.chat_format == 'chatml', _ERROR_BAD_CHAT_FORMAT
AssertionError: We detect you are probably using the pretrained model (rather than chat model) for chatting, since the chat_format in generation_config is not "chatml".
If you are directly using the model downloaded from Huggingface, please make sure you are using our "Qwen/Qwen-7B-Chat" Huggingface model (rather than "Qwen/Qwen-7B") when you call model.chat().
```
我们检测到您可能在使用预训练模型（而非chat模型）进行多轮chat，因为您当前在generation_config指定的chat_format，并未设置为我们在对话中所支持的"chatml"格式。
如果您在直接使用我们从Huggingface提供的模型，请确保您在调用model.chat()时，使用的是"Qwen/Qwen-7B-Chat"模型（而非"Qwen/Qwen-7B"预训练模型）。

**Comment by JustinLin610** [comment]
base模型只是基础的语言模型，我们不建议将其当chat模型使用。按照web demo本身提供的方法使用是支持多轮对话输出的

**Comment by txy6666yr** [comment]
> base模型只是基础的语言模型，我们不建议将其当chat模型使用。按照web demo本身提供的方法使用是支持多轮对话输出的

好的 谢谢

**Comment by ILOFI** [comment]
> 

请问下这个问题解决了吗？我在base模型上用web demo跑的时候，即使把那行assert注释掉还是会报错：
  File "modeling_qwen.py", line 1060, in chat_stream
    max_window_size = generation_config.max_window_size
AttributeError: 'GenerationConfig' object has no attribute 'max_window_size'
