### ISSUE TITLE
💡 [REQUEST] - 如何控制结果尽量用Markdown格式展示？

### ISSUE THREAD

**Issue by huajianmao** [QwenLM/Qwen-7B#179]
### 摘要 | Summary

用ReAct方式实现插件机制，希望结果能以Markdown格式进行输出，有什么建议吗？

### 基本示例 | Basic Example

<img width="1288" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/1352072/a0ac7652-0b6e-475a-bda1-a5459486c8c3">

### 缺陷 | Drawbacks

没有按照markdown格式输出，图片无法直接在结果里展示。

ReAct Prompt 基本和example里的一致。
也尝试了在Final Answer里加了 `markdown format is preferred in the final answer`，但也没啥效果

<img width="1140" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/1352072/c2065915-00ff-474e-bb67-0e48f5234db8">

**Comment by JianxinMa** [comment]
思路1：规则后处理。拿到文生图插件返回的 image_url、在 Final Answer 生成结束后，看下 ` ![.*](image_url) ` 是否存在于 Final Answer 中，不在就 append 到 Fianl Answer。

思路2（没有思路1可靠）：采用 in-context learning 的思路。通过贴几个参考思路，教会模型按特定格式输出。

比如，给 qwen-7b demo 输入如下 prompt（注意在实际的 question 前拼了另一个 question 作为 in-context example）：
```
Answer the following questions as best you can. You have access to the following tools:

image_gen: Call this tool to interact with the 通义万相 API. What is the 通义万相 API useful for? 通义万相是一个AI绘画（图像生成）服务，输入文本描述，返回根据文本作画得到的图片的URL Parameters: [{"name": "query", "description": "中文关键词，描述了希望图像具有什么内容", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [quark_search,image_gen]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!


Question:我画个五彩斑斓的黑。
Thought: 我应该使用通义万相 API 来生成图片。
Action: image_gen
Action Input: {"query": "五彩斑斓的黑"}
Observation: {"code": 200, "message": "success", "data": "https://oss.xxx.com/image.jpg"}
Thought: 根据 API 返回结果，我已经成功生成了五彩斑斓的黑的图片。
Final Answer: 成功生成了五彩斑斓的黑的图片。 ![](https://oss.xxx.com/image.jpg)


Question: 帮我画一张恐龙在天上飞的图画
```

则 qwen-7b 会输出如下符合要求的内容：
```
Thought: 我应该使用通义万相 API 来生成图片。
Action: image_gen
Action Input: {"query": "恐龙在天上飞"}
Observation: {"code": 200, "message": "success", "data": "[https://oss.xxx.com/image.jpg"}](https://oss.xxx.com/image.jpg%22%7D)
Thought: 根据 API 返回结果，我已经成功生成了恐龙在天上飞的图画。
Final Answer: 成功生成了恐龙在天上飞的图画。![](https://oss.xxx.com/image.jpg)
```

**Comment by huajianmao** [comment]
思路1、思路2感觉有些 case dependent，必须要判断出这个场景下是预期生成一张图片的，才好做这个动作。

尝试了类似思路1的另外一种方案就是在plugin生成结果后，作为Observation的内容再喂给模型，但也没有成功返回。

<img width="1038" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/1352072/9a68dda0-5e8e-4eb6-aaab-7eebe5bf7dd5">


此时构造的ReAct Prompt内容如下：
<img width="1140" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/1352072/f29d82c4-1a1f-467e-896c-f8963f3d5b82">
