### ISSUE TITLE
请求int4量化模型

### ISSUE THREAD

**Issue by hutianyu2006** [QwenLM/Qwen-7B#18]
未量化的模型会导致在RAM容量较少的情况下占满RAM导致崩溃（例如Google Colaboratory和Kaggle Notebook环境），所以在此希望官方能像ChatGLM-6B一样在Huggingface上上传一份int4量化后的模型。
![image](https://github.com/QwenLM/Qwen-7B/assets/52768188/274a785b-4abc-4e91-8f1a-2959783d184b)

**Comment by JianxinMa** [comment]
int4效果一般会有较大损失。如果只是想体验对话效果，可以在 modelscope 免费体验：https://modelscope.cn/studios/qwen/Qwen-7B-Chat-Demo/summary

**Comment by hutianyu2006** [comment]
有的时候，用户可能对逻辑推理之类的能力并不在意（没人会让猫娘去写泰勒展开），但是对低成本的私有化部署的需求却十分迫切（不是每个人都有RTX4090）。诚然，int4模型的确会对生成效果造成较大损失（我在折腾ChatGLM系列模型时已经领教过了），但是如果不涉及太多逻辑推理之类的内容，其实用户用起来没什么区别。在modelscope上进行免费体验固然是一个不错的选择，但是在注册完modelscope之后还要注册阿里云账号，相当烦。综上所述，我个人认为官方还是有必要提供一份int4量化模型的。


（p.s. 量化成int4之后MMLU分还比LlaMa-13B高，说明量化完效果也不算太差！）



---原始郵件---
寄件人： "Jianxin ***@***.***&gt;
傳送時間： 2023年8月3日(週四) 晚上10:20
收件人： ***@***.***&gt;;
抄送： "Hu ***@***.******@***.***&gt;;
主旨： Re: [QwenLM/Qwen-7B] 请求int4量化模型 (Issue #18)




 
int4效果一般会有较大损失。如果只是想体验对话效果，可以在 modelscope 免费体验：https://modelscope.cn/studios/qwen/Qwen-7B-Chat-Demo/summary

**Comment by JianxinMa** [comment]
了解~ int4 在 readme 里好像有相关内容，我找相关同事确认下是否可用。btw，我刚用新手机号试了下，注册 modelscope 体验 demo 似乎不需要阿里云账号，注册环节不要点击“领取算力礼包”、跳过绑定阿里云账号的环节即可。

**Comment by hutianyu2006** [comment]
1.我的意思是说像ChatGLM一样在HuggingFace上放一个预先int4量化过的模型，不然RAM较小的环境连加载模型都做不到
2.demo体验了一下，但是我发现可以免auth token通过gradio api使用demo，如果是有意为之，那我感觉登录完全多此一举，如果是无意为之，建议想办法加上auth token避免滥用
3.另外报个modelscope的bug，看似手机号支持那么多国家，实际上只支持+86，因为别的国家手机号都会格式错误（验证码正常收，在填写账号名称的地方会报错）

**Comment by JustinLin610** [comment]
之前应该是默认fp32很容易爆显存，现在打开应该能节省。NF4和Int8也都可以使用。RAM比较小这个问题，我们后续直接做个量化版本的ckpt提供出来。

**Comment by hutianyu2006** [comment]
那么希望量化版本的ckpt能够尽快放上HF，这个issue我先关了。
