### ISSUE TITLE
[HELP] 单卡可以支持多用户并发推理么？

### ISSUE THREAD

**Issue by jasperwangpro** [QwenLM/Qwen-7B#183]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

单卡，多用户目前是排队一个一个推理

### 期望行为 | Expected Behavior

有没有办法支持单卡并发推理，比如增加进程数
看了之前的issue，qwen在不打开flash_attn时，支持每秒27个字符的推理速度，如果部署在线业务，除了增加卡的数量，有没有办法优化单卡的性能呢？

希望大佬能提供点资料或者思路，不胜感激～

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by xusenlinzy** [comment]
可以考虑使用 [vLLM](https://github.com/vllm-project/vllm)  ，使用方式：https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md

**Comment by abrahamhoo** [comment]
我也遇到了并发的问题。
多个用户单卡并发推理，采用官方的流式输出方式，socket调用。
`for response in model.chat_stream(tokenizer, query, history=history):
            yield query, response`
发现模型会提前输出eos token。

确认没有达到输出的max_len，GPU使用率也没有到100%。

**Comment by bh4ffu** [comment]
@xusenlinzy 感谢！

**Comment by bh4ffu** [comment]
@xusenlinzy 感谢~
