### ISSUE TITLE
💡验证了一下用Qwen支撑插件的能力，整体效果还不错，期待Qwen能推出更强的模型

### ISSUE THREAD

**Issue by huajianmao** [QwenLM/Qwen-7B#186]
### 相关Issues | Reference Issues

#179 

### 摘要 | Summary

利用Qwen的函数解析能力，验证性的实现了一下类插件功能（远不及openai官方的插件机制强大），整体效果还挺好的。

主要干了两件事：
 1. 后端部分：1）给Qwen套上openai的壳；2）支持function call功能（支持stream和非stream模式）
 2. 前端部分：1）粗糙的在前端整合了插件能力；2）为了配合插件功能，提供了个简易的plugin服务（只验证性的提供了两个插件 LoL）
 
当前尝试实现的插件（目前还偏玩具性质，以验证性为主）：
 - [利用SDXL生成图片](https://github.com/llmapp/openai.mini/blob/0b477708622a7976ebd29c4b867868e927dce88d/app/backend/plugin/plugins/SDXL.py)（后端部分实现了[openai接口](https://github.com/llmapp/openai.mini#create-image)）
 - 基于Langchain的`WolframAlphaAPIWrapper`，对接了[`wolfram.run`](https://github.com/llmapp/openai.mini/blob/master/app/backend/plugin/plugins/Wolfram.py)
 - [节假日查询](https://github.com/llmapp/openai.mini/blob/master/app/backend/plugin/plugins/Holiday.py)
 - [汇率查询](https://github.com/llmapp/openai.mini/blob/master/app/backend/plugin/plugins/Currency.py)

可以通过在[plugins目录](https://github.com/llmapp/openai.mini/tree/master/app/backend/plugin/plugins)里定义自己的插件，要求文件名和插件的类型保持一致。

代码在：[llmapp/openai.mini](https://github.com/llmapp/openai.mini)

### 基本示例 | Basic Example

效果上（视觉上），实现了类似ChatGPT里的插件功能，截图如下：
![image](https://github.com/QwenLM/Qwen-7B/assets/1352072/3d414174-13ad-4dc5-aa92-a9ea546c8b0b)

### 缺陷 | Drawbacks

期待Qwen推出更加强大的开源模型，比如：
1. function call的结果渲染能力希望能够增强。例如 #179 里的图片展示问题。
2. 更强的上下文能力，试验了一下，感觉开了functions call能力以后，上下文的理解能力会减弱。（不排除是我实现function call的机制问题）
3. 再比如，上面截图里的第一个画图，插件已经能够正确返回结果了，但是Qwen的回答：`很抱歉，根据您提供的信息，我无法提供您所需的答案。`

但总体上，特别是在从问题到函数识别的能力上，已经比很多其他的开源模型强了。

**Comment by JianxinMa** [comment]
此外，我们会保留 Thought、Action、Observation 的内容在对话历史中（至少 ReAct_Instruction 之后的对话都会保留这些信息）。上面贴的示例没有把这部分展示出来。比如上面的示例2，其实应该是：

```
Query 0：你好
Response 0：您好。

Query 1: ReAct_Instruction + 周杰伦是谁
Response 1: Thought: xxx
Action: xxx
Action Input: xxx
Observation: xxx
Final Answer: 周杰伦是台湾歌手。

Query 2：他老婆是谁
Response 2: ...
```

**Comment by JianxinMa** [comment]
还有一个比较复杂的细节是：我自己在产品中实现时，其实并不会用 chat 接口实现，而是会用 generate 接口、使用 text completion 的思路去实现 ReAct。前者 chat 接口的实现类似 LangChain 用 ChatGPT 的方式，而后者 generate 接口的实现类似 LangChain 用 text-davinci-003 的方式。后者更接近训练数据的构造方式，但因为后者解释起来较复杂，所以我暂时没有在 examples 下放这个示例，我后面会抽空也补下。

**Comment by huajianmao** [comment]
> 关于 2，上下文是指之前的对话历史吗？我看了下 llmapp 的实现，注意到 ReAct 那一大段 instruction （"Begin!" 及之前那些详细的指令）现在似乎总是拼在最新的一个 query 里的 —— 这段 instruction 太长，会使模型注意不到之前的对话历史。
> 
> 举例来说，现在似乎是在处理最新一个 query 时，输入是：
> 
> ```
> Query 0：你好
> Response 0：您好。
> 
> Query 1: 周杰伦是谁
> Response 1: 周杰伦是台湾歌手。
> 
> Query 2：ReAct_Instruction + 他老婆是谁
> Response 2: （此时qwen-7b 可能会忘记“他”指周杰伦）
> ```
> 
> 而我内部实现时，会刻意把 ReAct_Instruction 拼接在倒数第二个 query，如下：
> 
> ```
> Query 0：你好
> Response 0：您好。
> 
> Query 1: ReAct_Instruction + 周杰伦是谁
> Response 1: 周杰伦是台湾歌手。
> 
> Query 2：他老婆是谁
> Response 2: （此时一般 qwen-7b 都能知道“他”指周杰伦）
> ```
> 
> 当然，我们也确实有观察到多轮对话下表现可能下降，这也是我们目前的重点优化方向之一。

react指令是只拼了最后一次user发起的带functions的chat开始，以及之后的多轮含function_call的assistant消息和function消息的拼接。最后一次之前的消息并没有丢失，都作为history传给chat的。不过的确有可能是指令太长，导致这种情况。我明天试试您的方案，在倒数第二个query里拼react。

另外，从#179的截图来看，我的这种实现下，qwen是能否发现上下文信息的😂

**Comment by huajianmao** [comment]
> 还有一个比较复杂的细节是：我自己在产品中实现时，其实并不会用 chat 接口实现，而是会用 generate 接口、使用 text completion 的思路去实现 ReAct。前者 chat 接口的实现类似 LangChain 用 ChatGPT 的方式，而后者 generate 接口的实现类似 LangChain 用 text-davinci-003 的方式。后者更接近训练数据的构造方式，但因为后者解释起来较复杂，所以我暂时没有在 examples 下放这个示例，我后面会抽空也补下。

嗯，期待官方提供的例子。

**Comment by huajianmao** [comment]
感谢详细的解释

**Comment by tanhzongbei** [comment]
我想请问下，他有多轮的能力吗？ 查询北京的天气，基本react都能实现；但是“北京和深圳哪个地方天气好”，这个我试验了这个模型好像是没法理解，得到2个查询的建议

**Comment by JianxinMa** [comment]
> 我想请问下，他有多轮的能力吗？ 查询北京的天气，基本react都能实现；但是“北京和深圳哪个地方天气好”，这个我试验了这个模型好像是没法理解，得到2个查询的建议

多轮是指在一个回答中调用多次插件吗？这一版模型没有专门优化这个能力，预计下一版模型能改善。当前的模型，需要靠in-context examples引出这种多次调用的能力，见 https://github.com/QwenLM/Qwen-7B/issues/162
