### ISSUE TITLE
运行python openai_api.py后，调用api报错

### ISSUE THREAD

**Issue by jackaihfia2334** [QwenLM/Qwen-7B#191]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

按照官方readme执行

import openai
openai.api_base = "http://localhost:8000/v1"
openai.api_key = "none"
for chunk in openai.ChatCompletion.create(
    model="Qwen-7B",
    messages=[
        {"role": "user", "content": "你好"}
    ],
    stream=True
):
    if hasattr(chunk.choices[0].delta, "content"):
        print(chunk.choices[0].delta.content, end="", flush=True)

报错如下
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File /usr/local/lib/python3.10/dist-packages/urllib3/response.py:761, in HTTPResponse._update_chunk_length(self)
    760 try:
--> 761     self.chunk_left = int(line, 16)
    762 except ValueError:
    763     # Invalid chunked protocol response, abort.

ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

InvalidChunkLength                        Traceback (most recent call last)
File /usr/local/lib/python3.10/dist-packages/urllib3/response.py:444, in HTTPResponse._error_catcher(self)
    443 try:
--> 444     yield
    446 except SocketTimeout:
    447     # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but
    448     # there is yet no clean way to get at it from this context.

File /usr/local/lib/python3.10/dist-packages/urllib3/response.py:828, in HTTPResponse.read_chunked(self, amt, decode_content)
    827 while True:
--> 828     self._update_chunk_length()
    829     if self.chunk_left == 0:
...
--> 818     raise ChunkedEncodingError(e)
    819 except DecodeError as e:
    820     raise ContentDecodingError(e)

ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?3703d258-7c92-4ad5-9df2-b3e5c7ac65fb) or open in a [text editor](command:workbench.action.openLargeOutput?3703d258-7c92-4ad5-9df2-b3e5c7ac65fb). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers:4.31.0
- PyTorch:2.1.0a0+b5021ba
- CUDA:12.1
```

**Comment by RipperTs** [comment]
我也遇到了相同的情况，懒得去检查问题了，对照 `ChatGLM2-6B` 中的 `openai_api.py` 简单的改了改
```python
import os, sys
sys.path.append(os.getcwd())
import time
import torch
import uvicorn
from pydantic import BaseModel, Field
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Literal, Optional, Union
from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM
from transformers.generation import GenerationConfig
from sse_starlette.sse import ServerSentEvent, EventSourceResponse


@asynccontextmanager
async def lifespan(app: FastAPI): # collects GPU memory
    yield
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.ipc_collect()


app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ModelCard(BaseModel):
    id: str
    object: str = "model"
    created: int = Field(default_factory=lambda: int(time.time()))
    owned_by: str = "owner"
    root: Optional[str] = None
    parent: Optional[str] = None
    permission: Optional[list] = None


class ModelList(BaseModel):
    object: str = "list"
    data: List[ModelCard] = []


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class DeltaMessage(BaseModel):
    role: Optional[Literal["user", "assistant", "system"]] = None
    content: Optional[str] = None


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[ChatMessage]
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    max_length: Optional[int] = None
    stream: Optional[bool] = False


class ChatCompletionResponseChoice(BaseModel):
    index: int
    message: ChatMessage
    finish_reason: Literal["stop", "length"]


class ChatCompletionResponseStreamChoice(BaseModel):
    index: int
    delta: DeltaMessage
    finish_reason: Optional[Literal["stop", "length"]]


class ChatCompletionResponse(BaseModel):
    model: str
    object: Literal["chat.completion", "chat.completion.chunk"]
    choices: List[Union[ChatCompletionResponseChoice, ChatCompletionResponseStreamChoice]]
    created: Optional[int] = Field(default_factory=lambda: int(time.time()))


@app.get("/v1/models", response_model=ModelList)
async def list_models():
    global model_args
    model_card = ModelCard(id="gpt-3.5-turbo")
    return ModelList(data=[model_card])


@app.post("/v1/chat/completions", response_model=ChatCompletionResponse)
async def create_chat_completion(request: ChatCompletionRequest):
    global model, tokenizer

    if request.messages[-1].role != "user":
        raise HTTPException(status_code=400, detail="Invalid request")
    query = request.messages[-1].content

    prev_messages = request.messages[:-1]
    # Temporarily, the system role does not work as expected. We advise that you write the setups for role-play in your query.
    if len(prev_messages) > 0 and prev_messages[0].role == "system":
        query = prev_messages.pop(0).content + query

    history = []
    if len(prev_messages) % 2 == 0:
        for i in range(0, len(prev_messages), 2):
            if prev_messages[i].role == "user" and prev_messages[i+1].role == "assistant":
                history.append([prev_messages[i].content, prev_messages[i+1].content])
            else:
                raise HTTPException(status_code=400, detail="Invalid request.")
    else:
        raise HTTPException(status_code=400, detail="Invalid request.")

    if request.stream:
        generate = predict(query, history, request.model)
        return EventSourceResponse(generate, media_type="text/event-stream")

    response, _ = model.chat_stream(tokenizer, query, history=history)
    choice_data = ChatCompletionResponseChoice(
        index=0,
        message=ChatMessage(role="assistant", content=response),
        finish_reason="stop"
    )

    return ChatCompletionResponse(model=request.model, choices=[choice_data], object="chat.completion")


async def predict(query: str, history: List[List[str]], model_id: str):
    global model, tokenizer

    choice_data = ChatCompletionResponseStreamChoice(
        index=0,
        delta=DeltaMessage(role="assistant"),
        finish_reason=None
    )
    chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
    yield "{}".format(chunk.json(exclude_unset=True))

    current_length = 0

    for new_response in model.chat_stream(tokenizer, query, history):
        if len(new_response) == current_length:
            continue

        new_text = new_response[current_length:]
        current_length = len(new_response)

        choice_data = ChatCompletionResponseStreamChoice(
            index=0,
            delta=DeltaMessage(content=new_text),
            finish_reason=None
        )
        chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
        yield "{}".format(chunk.json(exclude_unset=True))


    choice_data = ChatCompletionResponseStreamChoice(
        index=0,
        delta=DeltaMessage(),
        finish_reason="stop"
    )
    chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
    yield "{}".format(chunk.json(exclude_unset=True))
    yield '[DONE]'


if __name__ == '__main__':
    model_name = '.\\Qwen\\Qwen-7B-Chat'
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from transformers.generation import GenerationConfig

    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", trust_remote_code=True).eval()
    model.generation_config = GenerationConfig.from_pretrained(model_name, trust_remote_code=True)
        
    uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)
```

依赖版本：
```
protobuf
transformers==4.30.2
cpm_kernels
torch>=2.0
gradio
mdtex2html
sentencepiece
accelerate
sse-starlette
streamlit>=1.24.0
pydantic==1.10.11
```
请重点关注 `pydantic` 的版本，因为我使用了旧版的函数 `chunk.json()`  
希望对你有用！

**Comment by yangapku** [comment]
@jackaihfia2334 您好，这个问题我这里并没有能够复现出来哈，可以正常出结果。可能大概率还是和环境版本（尤其是上面 @RipperTs 提到的pydantic版本）有关系，我这里也贴一下我的运行环境，如果您这边还有问题，可以尝试和下面的环境对齐哈：
```
Package                       Version
----------------------------- ------------
accelerate                    0.21.0
aiohttp                       3.8.5
aiosignal                     1.3.1
annotated-types               0.5.0
anyio                         3.7.1
asttokens                     2.2.1
async-timeout                 4.0.3
attrs                         23.1.0
backcall                      0.2.0
bitsandbytes                  0.41.1
certifi                       2022.12.7
charset-normalizer            2.1.1
click                         8.1.6
cmake                         3.25.0
decorator                     5.1.1
dropout-layer-norm            0.1
einops                        0.6.1
exceptiongroup                1.1.3
executing                     1.2.0
fastapi                       0.101.1
filelock                      3.9.0
flash-attn                    1.0.8
frozenlist                    1.4.0
fsspec                        2023.6.0
h11                           0.14.0
huggingface-hub               0.16.4
idna                          3.4
ipython                       8.14.0
jedi                          0.19.0
Jinja2                        3.1.2
lit                           15.0.7
MarkupSafe                    2.1.2
matplotlib-inline             0.1.6
mpmath                        1.2.1
multidict                     6.0.4
networkx                      3.0
ninja                         1.11.1
numpy                         1.24.1
openai                        0.27.8
packaging                     23.1
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.3.0
pip                           23.2.1
prompt-toolkit                3.0.39
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pydantic                      2.1.1
pydantic_core                 2.4.0
Pygments                      2.16.0
PyYAML                        6.0.1
regex                         2023.6.3
requests                      2.28.1
rotary-emb                    0.1
safetensors                   0.3.1
scipy                         1.11.1
setuptools                    68.0.0
six                           1.16.0
sniffio                       1.3.0
sse-starlette                 1.6.5
stack-data                    0.6.2
starlette                     0.27.0
sympy                         1.11.1
tiktoken                      0.4.0
tokenizers                    0.13.3
torch                         2.0.1+cu118
torchaudio                    2.0.2+cu118
torchvision                   0.15.2+cu118
tqdm                          4.65.0
traitlets                     5.9.0
transformers                  4.31.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.7.1
urllib3                       1.26.13
uvicorn                       0.23.2
wcwidth                       0.2.6
wheel                         0.41.1
yarl                          1.9.2
```
python版本为3.10

**Comment by jackaihfia2334** [comment]
> @jackaihfia2334 您好，这个问题我这里并没有能够复现出来哈，可以正常出结果。可能大概率还是和环境版本（尤其是上面 @RipperTs 提到的pydantic版本）有关系，我这里也贴一下我的运行环境，如果您这边还有问题，可以尝试和下面的环境对齐哈：
> 
> ```
> Package                       Version
> ----------------------------- ------------
> accelerate                    0.21.0
> aiohttp                       3.8.5
> aiosignal                     1.3.1
> annotated-types               0.5.0
> anyio                         3.7.1
> asttokens                     2.2.1
> async-timeout                 4.0.3
> attrs                         23.1.0
> backcall                      0.2.0
> bitsandbytes                  0.41.1
> certifi                       2022.12.7
> charset-normalizer            2.1.1
> click                         8.1.6
> cmake                         3.25.0
> decorator                     5.1.1
> dropout-layer-norm            0.1
> einops                        0.6.1
> exceptiongroup                1.1.3
> executing                     1.2.0
> fastapi                       0.101.1
> filelock                      3.9.0
> flash-attn                    1.0.8
> frozenlist                    1.4.0
> fsspec                        2023.6.0
> h11                           0.14.0
> huggingface-hub               0.16.4
> idna                          3.4
> ipython                       8.14.0
> jedi                          0.19.0
> Jinja2                        3.1.2
> lit                           15.0.7
> MarkupSafe                    2.1.2
> matplotlib-inline             0.1.6
> mpmath                        1.2.1
> multidict                     6.0.4
> networkx                      3.0
> ninja                         1.11.1
> numpy                         1.24.1
> openai                        0.27.8
> packaging                     23.1
> parso                         0.8.3
> pexpect                       4.8.0
> pickleshare                   0.7.5
> Pillow                        9.3.0
> pip                           23.2.1
> prompt-toolkit                3.0.39
> psutil                        5.9.5
> ptyprocess                    0.7.0
> pure-eval                     0.2.2
> pydantic                      2.1.1
> pydantic_core                 2.4.0
> Pygments                      2.16.0
> PyYAML                        6.0.1
> regex                         2023.6.3
> requests                      2.28.1
> rotary-emb                    0.1
> safetensors                   0.3.1
> scipy                         1.11.1
> setuptools                    68.0.0
> six                           1.16.0
> sniffio                       1.3.0
> sse-starlette                 1.6.5
> stack-data                    0.6.2
> starlette                     0.27.0
> sympy                         1.11.1
> tiktoken                      0.4.0
> tokenizers                    0.13.3
> torch                         2.0.1+cu118
> torchaudio                    2.0.2+cu118
> torchvision                   0.15.2+cu118
> tqdm                          4.65.0
> traitlets                     5.9.0
> transformers                  4.31.0
> transformers-stream-generator 0.0.4
> triton                        2.0.0
> typing_extensions             4.7.1
> urllib3                       1.26.13
> uvicorn                       0.23.2
> wcwidth                       0.2.6
> wheel                         0.41.1
> yarl                          1.9.2
> ```
> 
> python版本为3.10

感谢解答，已通过更新包版本解决

**Comment by ArtificialZeng** [comment]
> @jackaihfia2334 您好，这个问题我这里并没有能够复现出来哈，可以正常出结果。可能大概率还是和环境版本（尤其是上面 @RipperTs 提到的pydantic版本）有关系，我这里也贴一下我的运行环境，如果您这边还有问题，可以尝试和下面的环境对齐哈：
> 
> ```
> Package                       Version
> ----------------------------- ------------
> accelerate                    0.21.0
> aiohttp                       3.8.5
> aiosignal                     1.3.1
> annotated-types               0.5.0
> anyio                         3.7.1
> asttokens                     2.2.1
> async-timeout                 4.0.3
> attrs                         23.1.0
> backcall                      0.2.0
> bitsandbytes                  0.41.1
> certifi                       2022.12.7
> charset-normalizer            2.1.1
> click                         8.1.6
> cmake                         3.25.0
> decorator                     5.1.1
> dropout-layer-norm            0.1
> einops                        0.6.1
> exceptiongroup                1.1.3
> executing                     1.2.0
> fastapi                       0.101.1
> filelock                      3.9.0
> flash-attn                    1.0.8
> frozenlist                    1.4.0
> fsspec                        2023.6.0
> h11                           0.14.0
> huggingface-hub               0.16.4
> idna                          3.4
> ipython                       8.14.0
> jedi                          0.19.0
> Jinja2                        3.1.2
> lit                           15.0.7
> MarkupSafe                    2.1.2
> matplotlib-inline             0.1.6
> mpmath                        1.2.1
> multidict                     6.0.4
> networkx                      3.0
> ninja                         1.11.1
> numpy                         1.24.1
> openai                        0.27.8
> packaging                     23.1
> parso                         0.8.3
> pexpect                       4.8.0
> pickleshare                   0.7.5
> Pillow                        9.3.0
> pip                           23.2.1
> prompt-toolkit                3.0.39
> psutil                        5.9.5
> ptyprocess                    0.7.0
> pure-eval                     0.2.2
> pydantic                      2.1.1
> pydantic_core                 2.4.0
> Pygments                      2.16.0
> PyYAML                        6.0.1
> regex                         2023.6.3
> requests                      2.28.1
> rotary-emb                    0.1
> safetensors                   0.3.1
> scipy                         1.11.1
> setuptools                    68.0.0
> six                           1.16.0
> sniffio                       1.3.0
> sse-starlette                 1.6.5
> stack-data                    0.6.2
> starlette                     0.27.0
> sympy                         1.11.1
> tiktoken                      0.4.0
> tokenizers                    0.13.3
> torch                         2.0.1+cu118
> torchaudio                    2.0.2+cu118
> torchvision                   0.15.2+cu118
> tqdm                          4.65.0
> traitlets                     5.9.0
> transformers                  4.31.0
> transformers-stream-generator 0.0.4
> triton                        2.0.0
> typing_extensions             4.7.1
> urllib3                       1.26.13
> uvicorn                       0.23.2
> wcwidth                       0.2.6
> wheel                         0.41.1
> yarl                          1.9.2
> ```
> 
> python版本为3.10

我就和你的一样哇  pydantic 2.1.1

**Comment by ArtificialZeng** [comment]
> ```python
> import os, sys
> sys.path.append(os.getcwd())
> import time
> import torch
> import uvicorn
> from pydantic import BaseModel, Field
> from fastapi import FastAPI, HTTPException
> from fastapi.middleware.cors import CORSMiddleware
> from contextlib import asynccontextmanager
> from typing import Any, Dict, List, Literal, Optional, Union
> from transformers import AutoTokenizer, AutoModel, AutoModelForCausalLM
> from transformers.generation import GenerationConfig
> from sse_starlette.sse import ServerSentEvent, EventSourceResponse
> 
> 
> @asynccontextmanager
> async def lifespan(app: FastAPI): # collects GPU memory
>     yield
>     if torch.cuda.is_available():
>         torch.cuda.empty_cache()
>         torch.cuda.ipc_collect()
> 
> 
> app = FastAPI(lifespan=lifespan)
> 
> app.add_middleware(
>     CORSMiddleware,
>     allow_origins=["*"],
>     allow_credentials=True,
>     allow_methods=["*"],
>     allow_headers=["*"],
> )
> 
> 
> class ModelCard(BaseModel):
>     id: str
>     object: str = "model"
>     created: int = Field(default_factory=lambda: int(time.time()))
>     owned_by: str = "owner"
>     root: Optional[str] = None
>     parent: Optional[str] = None
>     permission: Optional[list] = None
> 
> 
> class ModelList(BaseModel):
>     object: str = "list"
>     data: List[ModelCard] = []
> 
> 
> class ChatMessage(BaseModel):
>     role: Literal["user", "assistant", "system"]
>     content: str
> 
> 
> class DeltaMessage(BaseModel):
>     role: Optional[Literal["user", "assistant", "system"]] = None
>     content: Optional[str] = None
> 
> 
> class ChatCompletionRequest(BaseModel):
>     model: str
>     messages: List[ChatMessage]
>     temperature: Optional[float] = None
>     top_p: Optional[float] = None
>     max_length: Optional[int] = None
>     stream: Optional[bool] = False
> 
> 
> class ChatCompletionResponseChoice(BaseModel):
>     index: int
>     message: ChatMessage
>     finish_reason: Literal["stop", "length"]
> 
> 
> class ChatCompletionResponseStreamChoice(BaseModel):
>     index: int
>     delta: DeltaMessage
>     finish_reason: Optional[Literal["stop", "length"]]
> 
> 
> class ChatCompletionResponse(BaseModel):
>     model: str
>     object: Literal["chat.completion", "chat.completion.chunk"]
>     choices: List[Union[ChatCompletionResponseChoice, ChatCompletionResponseStreamChoice]]
>     created: Optional[int] = Field(default_factory=lambda: int(time.time()))
> 
> 
> @app.get("/v1/models", response_model=ModelList)
> async def list_models():
>     global model_args
>     model_card = ModelCard(id="gpt-3.5-turbo")
>     return ModelList(data=[model_card])
> 
> 
> @app.post("/v1/chat/completions", response_model=ChatCompletionResponse)
> async def create_chat_completion(request: ChatCompletionRequest):
>     global model, tokenizer
> 
>     if request.messages[-1].role != "user":
>         raise HTTPException(status_code=400, detail="Invalid request")
>     query = request.messages[-1].content
> 
>     prev_messages = request.messages[:-1]
>     # Temporarily, the system role does not work as expected. We advise that you write the setups for role-play in your query.
>     if len(prev_messages) > 0 and prev_messages[0].role == "system":
>         query = prev_messages.pop(0).content + query
> 
>     history = []
>     if len(prev_messages) % 2 == 0:
>         for i in range(0, len(prev_messages), 2):
>             if prev_messages[i].role == "user" and prev_messages[i+1].role == "assistant":
>                 history.append([prev_messages[i].content, prev_messages[i+1].content])
>             else:
>                 raise HTTPException(status_code=400, detail="Invalid request.")
>     else:
>         raise HTTPException(status_code=400, detail="Invalid request.")
> 
>     if request.stream:
>         generate = predict(query, history, request.model)
>         return EventSourceResponse(generate, media_type="text/event-stream")
> 
>     response, _ = model.chat_stream(tokenizer, query, history=history)
>     choice_data = ChatCompletionResponseChoice(
>         index=0,
>         message=ChatMessage(role="assistant", content=response),
>         finish_reason="stop"
>     )
> 
>     return ChatCompletionResponse(model=request.model, choices=[choice_data], object="chat.completion")
> 
> 
> async def predict(query: str, history: List[List[str]], model_id: str):
>     global model, tokenizer
> 
>     choice_data = ChatCompletionResponseStreamChoice(
>         index=0,
>         delta=DeltaMessage(role="assistant"),
>         finish_reason=None
>     )
>     chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
>     yield "{}".format(chunk.json(exclude_unset=True))
> 
>     current_length = 0
> 
>     for new_response in model.chat_stream(tokenizer, query, history):
>         if len(new_response) == current_length:
>             continue
> 
>         new_text = new_response[current_length:]
>         current_length = len(new_response)
> 
>         choice_data = ChatCompletionResponseStreamChoice(
>             index=0,
>             delta=DeltaMessage(content=new_text),
>             finish_reason=None
>         )
>         chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
>         yield "{}".format(chunk.json(exclude_unset=True))
> 
> 
>     choice_data = ChatCompletionResponseStreamChoice(
>         index=0,
>         delta=DeltaMessage(),
>         finish_reason="stop"
>     )
>     chunk = ChatCompletionResponse(model=model_id, choices=[choice_data], object="chat.completion.chunk")
>     yield "{}".format(chunk.json(exclude_unset=True))
>     yield '[DONE]'
> 
> 
> if __name__ == '__main__':
>     model_name = '.\\Qwen\\Qwen-7B-Chat'
>     from transformers import AutoModelForCausalLM, AutoTokenizer
>     from transformers.generation import GenerationConfig
> 
>     tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
>     model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", trust_remote_code=True).eval()
>     model.generation_config = GenerationConfig.from_pretrained(model_name, trust_remote_code=True)
>         
>     uvicorn.run(app, host='0.0.0.0', port=8000, workers=1)
> ```

 response, _ = model.chat_stream(tokenizer, query, history=history)
ValueError: too many values to unpack (expected 2)

**Comment by RipperTs** [comment]
> 

大概率依赖版本问题 https://github.com/QwenLM/Qwen-7B/issues/191#issuecomment-1678249682

**Comment by jackaihfia2334** [comment]
> > 
> 
> 大概率依赖版本问题 [#191 (comment)](https://github.com/QwenLM/Qwen-7B/issues/191#issuecomment-1678249682)

但是fastchat的依赖需要pydantic<2

**Comment by RipperTs** [comment]
可以在新建一个虚拟环境来单独运行 `openai_api.py` 
```bash
# 新建虚拟环境
python3 -m venv openai_venv

# 安装依赖
./openai_venv/bin/pip install fastapi uvicorn pydantic==2.1.1 openai sse_starlette

# 运行
./openai_venv/bin/python openai_api.py
```
如果是Windows：
```shell
# 进入虚拟环境
.\openai_venv\Scripts\active

# 正常安装即可
pip install ...
```
