### ISSUE TITLE
[HELP] QWenTokenizer not detected locally

### ISSUE THREAD

**Issue by nikjohn7** [QwenLM/Qwen-7B#196]
I am trying to load the Qwen model on a notebook with no internet access, so I cannot use the `trust_remote_code=True` param. I have downloaded the model repo from huggingface, and have all the files and scripts, but when I try to load the tokenizer, I get this error:

![Screenshot 2023-08-15 at 09.27.56.png](https://cdn-uploads.huggingface.co/production/uploads/64b71385509b109d0423ee96/hSkxWIasBoPhWyAVS_NeS.png)

Here, `qwen7b` is the path to downloaded qwen-7b-chat files from huggingface

I have all the necessary latest files from huggingface downloaded 

![Screenshot 2023-08-15 at 14.16.50.png](https://cdn-uploads.huggingface.co/production/uploads/64b71385509b109d0423ee96/xwXPjmgNc0W0_pw7xBuIC.png)

How do I resolve this?

**Comment by JianxinMa** [comment]
On "with no internet access, so I cannot use the `trust_remote_code=True` param", it seems that `trust_remote_code=True` is unrelated to internet access. The term 'remote' likely refers to code that is not part of the official transformers package."

**Comment by nikjohn7** [comment]
Thanks so much @JianxinMa and @JustinLin610 . I was unaware that the `rust_remote_code=True` was regardless of internet connectivity.
