### ISSUE TITLE
[BUG] <title>openai的接口有错误，启动不起来"POST /v1/chat/completions HTTP/1.1" 422 Unprocessable Entity

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#197]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

"POST /v1/chat/completions HTTP/1.1" 422 Unprocessable Entity

### 期望行为 | Expected Behavior

准确返回结果

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，建议您详细填写下复现方法和运行环境信息，便于我们进行排查。另外也请您先参考下我们在issue #191中的环境配置，尤其是pydantic版本，可以尝试对齐下各个库的版本，再观察下问题是否仍然存在。
