### ISSUE TITLE
💡看readme里有用dynamic_ntk阔中INPUT的介绍，请问模型训练时怎么用dynamic_ntk让输入字符长度能超过2046的长度

### ISSUE THREAD

**Issue by JohnZhuYX** [QwenLM/Qwen-7B#200]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by logicwong** [comment]
请问你的目的是？

1. 如果只是训练数据里包含少量超过2048的文本，那建议将文本截断到2048以下；
2. 如果你是想通过微调来提升模型的外推能力，那建议是线性插值+微调，这是业界比较成功的尝试。我们这边尚未尝试过ntk+微调

**Comment by fengcai24** [comment]
那为啥qwen使用ntk呢？ @logicwong
