### ISSUE TITLE
[BUG] 使用最新代码报错，代码更新存在问题？

### ISSUE THREAD

**Issue by wujindou** [QwenLM/Qwen-7B#202]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

昨天跑的时候还是很好的，今天跑的时候报错了。如下：

yield from f(*args, **kwargs)
  File "/tmp/ipykernel_28/3798775890.py", line 62, in predict
    for response in model.chat_stream(tokenizer, get_context(query,faiss_index,contents), history=task_history):
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B-Chat/07a819346221e3aa503aaa48fa18c8d19f9af882/modeling_qwen.py", line 1059, in stream_generator
    outputs.append(token.item())
RuntimeError: a Tensor with 521 elements cannot be converted to Scalar

### 期望行为 | Expected Behavior

是否是文件这两天更新了

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

no

**Comment by yangapku** [comment]
您好，请问可以提供更多关于的报错复现信息吗？您也可以通过在from_pretrained方法调用时，指定下revision参数，帮我们提供一个没有报错的commit，供我们对比和排查哈。

**Comment by wujindou** [comment]
找到问题了，chat_stream设置了do_sample = False , 看了别的回答下好像不支持，先关闭了
