### ISSUE TITLE
[BUG] 模型使用web_deo时，似乎对gradio的版本有要求<title>较低版本的gradio（如gradio==3.23.0）时，启动web_deo后，发送信息，模型似乎无法收到对应的请求信息。

### ISSUE THREAD

**Issue by xiaolvtongxue-zt** [QwenLM/Qwen-7B#207]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用最新版本 gradio==3.40.1；模型可以再网页上正常回复；
而使用较低版本的gradio（如gradio==3.23.0）时，启动web_deo后，发送信息，模型似乎无法收到对应的请求信息。

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.9
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
感谢反馈 我们也测试下版本。一般我们都建议使用最新版本

**Comment by xiaolvtongxue-zt** [comment]
> 感谢反馈 我们也测试下版本。一般我们都建议使用最新版本

使用不同版本是因为gradio通过API调用时，调用的格式和命令不尽相同。
