### ISSUE TITLE
plugin 微调数据

### ISSUE THREAD

**Issue by xiaobaibai1** [QwenLM/Qwen-7B#208]
### 摘要 | Summary

可以描述一下 plugin 的微调数据吗？以及数据的生成过程

### 基本示例 | Basic Example

希望了解一下 plugin 的微调数据，以及数据的生成过程

### 缺陷 | Drawbacks

希望了解一下 plugin 的微调数据，以及数据的生成过程

**Comment by JianxinMa** [comment]
如果是想了解 qwen plugin 的训练数据“长什么样”，那么可以参考 https://github.com/QwenLM/Qwen-7B/blob/main/examples/langchain_tooluse.ipynb 最后贴的几个 showcases。
- 一条样本的 query 就是 ReAct 的那一大堆 instruction 描述，包含用户提的 Question。
- 一条样本的 response 就是 Question 之后的 Thought （含）到 Final Answer（含）的内容。

如果是想了解我们是怎么“生产”出这种训练数据的，我可能不方便透露太多。只能说基本思路是 self-instruct/self-alignment：
- Step 1：模型生成插件描述、生成用户问题、生成基于ReAct的回答。
- Step 2：数据清洗，用各种手段清洗，得到较好的数据用于 SFT。
- 视情况循环 Step 1 & Step 2。

**Comment by Sanster** [comment]
@JianxinMa 请问 plugin 类型数据的数量级以及 api 的种类数方便分享么？
