### ISSUE TITLE
Languages in the pretrain

### ISSUE THREAD

**Issue by averkij** [QwenLM/Qwen-7B#211]
Hello 🖐️

Did you explicitly filter other languages (non English and non Chinese) from the pretrain dataset?

If not, what are proportions of them?

**Comment by GanjinZero** [comment]
Please refer to **tech_memo.me**

**Comment by averkij** [comment]
@GanjinZero Yeah, I've read it, but there is no information about language proportions there.

**Comment by Losin** [comment]
> @GanjinZero Yeah, I've read it, but there is no information about language proportions there.

The proportions of other languages (non English and non Chinese) are less than 2%.
