### ISSUE TITLE
基于Qwen-7B的LangChain有实现了吗？

### ISSUE THREAD

**Issue by EricKong1985** [QwenLM/Qwen-7B#212]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

就是提个问题，看大家有什么分享

### 期望行为 | Expected Behavior

就是提个问题，看大家有什么分享

### 复现方法 | Steps To Reproduce

就是提个问题，看大家有什么分享

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

基于Qwen-7B的LangChain有实现了吗？ 
有基于基于Aliyun云服务接口的实现？
看md写提供了OpenAI API格式的本地API部署方法
时候可以基于原来ChatGpt的LangChain，修改参数就可以实现？

**Comment by JianxinMa** [comment]
目前开源的版本仅部分兼容langchain：
- 如果是希望使用 langchain 的文档问答，可参考 modelscope 提供的使用[案例](https://zhuanlan.zhihu.com/p/650423460) 
- 如果是希望使用 langchain 的工具使用（函数调用），可参考此[文档](https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_prompt.md)。也可以考虑使用社区提供的实现，参见：
  - #186 
  - #47 
- 至于 langchain 的各种 autonomous agent 用法，目前这版 qwen-7b 没有专门优化过。

**Comment by JianxinMa** [comment]
"有基于基于Aliyun云服务接口的实现？" —— 实现文档问答应该没问题；但实现工具调用需要配置 stop word，需要注意 aliyun 接口是否已经开放此项配置。

"看md写提供了OpenAI API格式的本地API部署方法时候可以基于原来ChatGpt的LangChain，修改参数就可以实现？" —— 效果可能不会特别理想，因为这版 qwen-7b 没有针对 langchain 使用的 prompts 进行优化。
