### ISSUE TITLE
[BUG] 长文本理解的一些疑惑

### ISSUE THREAD

**Issue by huqiuser** [QwenLM/Qwen-7B#214]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

![image](https://github.com/QwenLM/Qwen-7B/assets/8498124/6b3bb052-898b-42d9-99ec-e3df22e8375c)

### 期望行为 | Expected Behavior

上图中的3.49是什么意思,没有看懂,麻烦解释一下.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by logicwong** [comment]
PPL
