### ISSUE TITLE
[BUG] <title>使用vllm进行推理部署时，流式对话输出错误token，比如'�'

### ISSUE THREAD

**Issue by LouisHeck** [QwenLM/Qwen-7B#215]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用vllm部署open ai形式的服务时，(python -m vllm.entrypoints.openai.api_server --model =/home/models/Qwen-7B-Chat)，
如果使用stream=True调用服务时，打印出来的token中会出现乱码'�'，我看官方说修复了，但是我用vllm推理时，还是出现问题。

请问是什么原因？该如何修改呢？

### 期望行为 | Expected Behavior

vllm推理时，流式输出不出现错误token'�'，并且汉字不丢失

### 复现方法 | Steps To Reproduce

1. 启动vllm的openai形式服务，python -m vllm.entrypoints.openai.api_server --model =/home/models/Qwen-7B-Chat
2. 使用openai进行流式调用
response = openai.ChatCompletion.create(
    model=model,
    messages=[{"role": "user", "content": prompt}],
    temperature=0,
    max_tokens=1024,
    stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"],
    stream=True  # again, we set stream=True
)
3. 打印response结果中可以发现有错误的token. '�'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
如果使用我们的api是不会输出乱码，可以看chat_stream的方法。乱码的原因是因为id to bytes，如果流式decode会解码byte出现不完整的汉字的问题。vllm的实现我们还没有去那边查看，得看下那边的实现情况了

**Comment by LouisHeck** [comment]
感谢回答，在仓库里的文档中找到一个方法，将config.json里面的"replace"替换为"ignore"，可以解决

**Comment by Luis-xu** [comment]
@LouisHeck 您好，我遇到了类似的问题，请问您修改的是哪一个config.json解决上面问题

**Comment by lin-xiaosheng** [comment]
@Luis-xu 您好，请问您解决这个问题了吗,我也找不到符合条件的config.json文件

**Comment by xinzaifeixiang1992** [comment]
> chat_stream
chat_stream方法在哪个文件里面呢
