### ISSUE TITLE
[BUG] <title>使用examples/react_demo.py中的方法，会无视问题内容强行使用工具

### ISSUE THREAD

**Issue by lizheray** [QwenLM/Qwen-7B#221]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

#186 

> 关于 2，上下文是指之前的对话历史吗？我看了下 llmapp 的实现，注意到 ReAct 那一大段 instruction （"Begin!" 及之前那些详细的指令）现在似乎总是拼在最新的一个 query 里的 —— 这段 instruction 太长，会使模型注意不到之前的对话历史。

> 还有一个比较复杂的细节是：我自己在产品中实现时，其实并不会用 chat 接口实现，而是会用 generate 接口、使用 text completion 的思路去实现 ReAct。前者 chat 接口的实现类似 LangChain 用 ChatGPT 的方式，而后者 generate 接口的实现类似 LangChain 用 text-davinci-003 的方式。后者更接近训练数据的构造方式，但因为后者解释起来较复杂，所以我暂时没有在 examples 下放这个示例，我后面会抽空也补下。

我用该回复提到的脚本，即examples/react_demo.py试了一下如下问题：
已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？
发现Qwen还是会使用google search。这个已经不是多轮对话理解不到的问题了吧？我已经直接把答案塞到问题里了，还是会使用工具。

### 期望行为 | Expected Behavior

已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？
对于这个问题，Qwen应该不使用任何工具直接回复。

### 复现方法 | Steps To Reproduce

我打印了一些中间步骤的日志，内容如下：

2023-08-21 07:45:11,408 [MainThread  ] [INFO ] Input: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Answer the following questions as best you can. You have access to the following tools:

google_search: Call this tool to interact with the 谷歌搜索 API. What is the 谷歌搜索 API useful for? 谷歌搜索是一个通用搜索引擎，可用于访问互联网、查询百科知识、了解时事新闻等。 Parameters: [{"name": "search_query", "description": "搜索关键词或短语", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [google_search]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？<|im_end|>
<|im_start|>assistant

2023-08-21 07:45:19,610 [MainThread  ] [INFO ] Output: Thought: 我应该使用google搜索查找相关信息。
Action: google_search
Action Input: {"search_query": "周杰伦 老婆 昆凌"}
Observation:
2023-08-21 07:45:22,951 [MainThread  ] [INFO ] Input: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Answer the following questions as best you can. You have access to the following tools:

google_search: Call this tool to interact with the 谷歌搜索 API. What is the 谷歌搜索 API useful for? 谷歌搜索是一个通用搜索引擎，可用于访问互联网、查询百科知识、了解时事新闻等。 Parameters: [{"name": "search_query", "description": "搜索关键词或短语", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [google_search]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？<|im_end|>
<|im_start|>assistant
Thought: 我应该使用google搜索查找相关信息。
Action: google_search
Action Input: {"search_query": "周杰伦 老婆 昆凌"}
Observation: Jay Chou is a Taiwanese singer, songwriter, record producer, rapper, actor, television personality, and businessman.
Thought:
2023-08-21 07:45:26,644 [MainThread  ] [INFO ] Output:  I now know the final answer.
Final Answer: 周杰伦的老婆是昆凌。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by JianxinMa** [comment]
对于这个问题，我试了下，gpt3.5也会调用搜索插件。因为在模型看来，用户提供的信息不一定是对的，模型认为需要自己搜一下核实下。如果明确不希望模型搜索，应该将相关工具关掉。

**Comment by JianxinMa** [comment]
也测试了下gpt4，gpt4同样会调用搜索工具。

**Comment by lizheray** [comment]
> 对于这个问题，我试了下，gpt3.5也会调用搜索插件。因为在模型看来，用户提供的信息不一定是对的，模型认为需要自己搜一下核实下。如果明确不希望模型搜索，应该将相关工具关掉。

感谢回复。我现在希望的是如果我直接给出上下文，应该从上下文中获取答案。获取不到才去使用工具。有什么建议的实现方法吗？

**Comment by JianxinMa** [comment]
> Answer the following questions as best you can. You have access to the following tools:
> 
> google_search: Call this tool to interact with the 谷歌搜索 API. What is the 谷歌搜索 API useful for? 谷歌搜索是一个通用搜索引擎，可用于访问互联网、查询百科知识、了解时事新闻等。 Parameters: [{"name": "search_query", "description": "搜索关键词或短语", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.
> 
> Use the following format:
> 
> Question: the input question you must answer Thought: you should always think about what to do Action: the action to take, should be one of [google_search] Action Input: the input to the action Observation: the result of the action ... (this Thought/Action/Action Input/Observation can be repeated zero or more times) Thought: I now know the final answer Final Answer: the final answer to the original input question
> 
> Begin!
> 
> Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？

试试加一句“不要使用工具”？我测了几个cases好像能work。比如：
```
Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？（不要使用工具。）
```

**Comment by lizheray** [comment]
> > Answer the following questions as best you can. You have access to the following tools:
> > google_search: Call this tool to interact with the 谷歌搜索 API. What is the 谷歌搜索 API useful for? 谷歌搜索是一个通用搜索引擎，可用于访问互联网、查询百科知识、了解时事新闻等。 Parameters: [{"name": "search_query", "description": "搜索关键词或短语", "required": true, "schema": {"type": "string"}}] Format the arguments as a JSON object.
> > Use the following format:
> > Question: the input question you must answer Thought: you should always think about what to do Action: the action to take, should be one of [google_search] Action Input: the input to the action Observation: the result of the action ... (this Thought/Action/Action Input/Observation can be repeated zero or more times) Thought: I now know the final answer Final Answer: the final answer to the original input question
> > Begin!
> > Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？
> 
> 试试加一句“不要使用工具”？我测了几个cases好像能work。比如：
> 
> ```
> Question: 已知：周杰伦的老婆是昆凌。请问：周杰伦的老婆是谁？（不要使用工具。）
> ```

我昨天试了类似的提示词，结果就是后续所有问题都不会使用工具了。我再想想别的办法吧
