### ISSUE TITLE
auto-gptq模块安装不了

### ISSUE THREAD

**Issue by running-frog** [QwenLM/Qwen-7B#224]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

D:\software\Qwen-7B>cd AutoGPTQ

D:\software\Qwen-7B\AutoGPTQ>pip install .
Processing d:\software\qwen-7b\autogptq
  Preparing metadata (setup.py) ... done
Requirement already satisfied: accelerate>=0.19.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (0.21.0)
Requirement already satisfied: datasets in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (2.13.0)
Requirement already satisfied: numpy in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (1.22.0)
Requirement already satisfied: rouge in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (1.0.1)
Requirement already satisfied: torch>=1.13.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (2.0.1+cu118)
Requirement already satisfied: safetensors in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (0.3.2)
Requirement already satisfied: transformers>=4.31.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (4.31.0)
Requirement already satisfied: peft in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from auto-gptq==0.4.1+cu118) (0.4.0)
Requirement already satisfied: packaging>=20.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from accelerate>=0.19.0->auto-gptq==0.4.1+cu118) (23.1)
Requirement already satisfied: psutil in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from accelerate>=0.19.0->auto-gptq==0.4.1+cu118) (5.9.5)
Requirement already satisfied: pyyaml in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from accelerate>=0.19.0->auto-gptq==0.4.1+cu118) (6.0.1)
Requirement already satisfied: filelock in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from torch>=1.13.0->auto-gptq==0.4.1+cu118) (3.12.2)
Requirement already satisfied: typing-extensions in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from torch>=1.13.0->auto-gptq==0.4.1+cu118) (4.7.1)
Requirement already satisfied: sympy in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from torch>=1.13.0->auto-gptq==0.4.1+cu118) (1.11.1)
Requirement already satisfied: networkx in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from torch>=1.13.0->auto-gptq==0.4.1+cu118) (3.0)
Requirement already satisfied: jinja2 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from torch>=1.13.0->auto-gptq==0.4.1+cu118) (3.1.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from transformers>=4.31.0->auto-gptq==0.4.1+cu118) (0.16.4)
Requirement already satisfied: regex!=2019.12.17 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from transformers>=4.31.0->auto-gptq==0.4.1+cu118) (2023.8.8)
Requirement already satisfied: requests in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from transformers>=4.31.0->auto-gptq==0.4.1+cu118) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from transformers>=4.31.0->auto-gptq==0.4.1+cu118) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from transformers>=4.31.0->auto-gptq==0.4.1+cu118) (4.66.1)
Requirement already satisfied: pyarrow>=8.0.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (12.0.1)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (0.3.6)
Requirement already satisfied: pandas in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (1.3.5)
Requirement already satisfied: xxhash in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (3.3.0)
Requirement already satisfied: multiprocess in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (0.70.14)
Requirement already satisfied: fsspec[http]>=2021.11.1 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (2023.6.0)
Requirement already satisfied: aiohttp in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from datasets->auto-gptq==0.4.1+cu118) (3.8.5)
Requirement already satisfied: six in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from rouge->auto-gptq==0.4.1+cu118) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from aiohttp->datasets->auto-gptq==0.4.1+cu118) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from requests->transformers>=4.31.0->auto-gptq==0.4.1+cu118) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from requests->transformers>=4.31.0->auto-gptq==0.4.1+cu118) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from requests->transformers>=4.31.0->auto-gptq==0.4.1+cu118) (2023.7.22)
Requirement already satisfied: colorama in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from tqdm>=4.27->transformers>=4.31.0->auto-gptq==0.4.1+cu118) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from jinja2->torch>=1.13.0->auto-gptq==0.4.1+cu118) (2.1.3)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from pandas->datasets->auto-gptq==0.4.1+cu118) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from pandas->datasets->auto-gptq==0.4.1+cu118) (2023.3)
Requirement already satisfied: mpmath>=0.19 in d:\software\qwen-7b\wpy64-310111\python-3.10.11.amd64\lib\site-packages (from sympy->torch>=1.13.0->auto-gptq==0.4.1+cu118) (1.2.1)
Building wheels for collected packages: auto-gptq
  Building wheel for auto-gptq (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      conda_cuda_include_dir D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\Lib\site-packages\nvidia/cuda_runtime/include
      running bdist_wheel
      running build
      running build_py
      running build_ext
      D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'autogptq_cuda_64' extension
      Emitting ninja build file D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: no work to do.
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\libs /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64 /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit_autogptq_cuda_64 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/autogptq_cuda_64.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/autogptq_cuda_kernel_64.obj /OUT:build\lib.win-amd64-cpython-310\autogptq_cuda_64.cp310-win_amd64.pyd /IMPLIB:D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_64.cp310-win_amd64.lib
        姝ｅ湪鍒涘缓搴\x93 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_64.cp310-win_amd64.lib 鍜屽\xaf硅薄 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_64.cp310-win_amd64.exp
      姝ｅ湪鐢熸垚浠ｇ爜
      宸插畬鎴愪唬鐮佺殑鐢熸垚
      building 'autogptq_cuda_256' extension
      Emitting ninja build file D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: no work to do.
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\libs /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64 /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit_autogptq_cuda_256 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/autogptq_cuda_256.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/autogptq_cuda_kernel_256.obj /OUT:build\lib.win-amd64-cpython-310\autogptq_cuda_256.cp310-win_amd64.pyd /IMPLIB:D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_256.cp310-win_amd64.lib
        姝ｅ湪鍒涘缓搴\x93 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_256.cp310-win_amd64.lib 鍜屽\xaf硅薄 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda\autogptq_cuda_256.cp310-win_amd64.exp
      姝ｅ湪鐢熸垚浠ｇ爜
      宸插畬鎴愪唬鐮佺殑鐢熸垚
      building 'exllama_kernels' extension
      Emitting ninja build file D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: no work to do.
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\libs /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64 /LIBPATH:D:\software\Qwen-7B\WPy64-310111\python-3.10.11.amd64\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit_exllama_kernels D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama/cuda_buffers.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama/cuda_func/column_remap.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama/cuda_func/q4_matmul.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama/cuda_func/q4_matrix.obj D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama/exllama_ext.obj /OUT:build\lib.win-amd64-cpython-310\exllama_kernels.cp310-win_amd64.pyd /IMPLIB:D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama\exllama_kernels.cp310-win_amd64.lib
        姝ｅ湪鍒涘缓搴\x93 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama\exllama_kernels.cp310-win_amd64.lib 鍜屽\xaf硅薄 D:\software\Qwen-7B\AutoGPTQ\build\temp.win-amd64-cpython-310\Release\autogptq_cuda/exllama\exllama_kernels.cp310-win_amd64.exp
      q4_matmul.obj : error LNK2001: 鏃犳硶瑙ｆ瀽鐨勫\xa4栭儴绗﹀彿 cublasHgemm
      build\lib.win-amd64-cpython-310\exllama_kernels.cp310-win_amd64.pyd : fatal error LNK1120: 1 涓\xaa鏃犳硶瑙ｆ瀽鐨 勫\xa4栭儴鍛戒护
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for auto-gptq
  Running setup.py clean for auto-gptq
Failed to build auto-gptq
ERROR: Could not build wheels for auto-gptq, which is required to install pyproject.toml-based projects

D:\software\Qwen-7B\AutoGPTQ>

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，请您填写下运行环境部分哈，特别是python和cuda版本
