### ISSUE TITLE
💡 [REQUEST] - <title>求教下怎么打印qwen的词表，对应到token的id，convert_tokens_to_ids()

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#230]
### 实现PR | Implementation PR

求教下怎么打印qwen的词表，对应到token的id，convert_tokens_to_ids()

### 摘要 | Summary

求教下怎么打印qwen的词表，对应到token的id，convert_tokens_to_ids()

### 基本示例 | Basic Example

求教下怎么打印qwen的词表，对应到token的id，convert_tokens_to_ids()

### 缺陷 | Drawbacks

求教下怎么打印qwen的词表，对应到token的id，convert_tokens_to_ids()

**Comment by nlfiasel** [comment]
huggingface的模型文件里面有词表，比如Qwen-7B-Chat的[qwen.tiktoken](https://huggingface.co/Qwen/Qwen-7B-Chat/raw/main/qwen.tiktoken)

**Comment by yangapku** [comment]
@ArtificialZeng 
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-7B-Chat", trust_remote_code=True)
tokens = []
for token_id in range(tokenizer.vocab_size):
    tokens.append(tokenizer.decode([token_id]))
```
