### ISSUE TITLE
[BUG] <title>官方web_demo有问题，请优化，AttributeError: 'GenerationConfig' object has no attribute 'chat_format'

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#238]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

(qwen) user@user-DGX-1-with-V100-32:~/base_models/Qwen-7B$ CUDA_VISIBLE_DEVICES=2 python web_demo.py
The model is automatically converting to fp16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:14<00:00,  1.79s/it]
Running on local URL:  http://0.0.0.0:18882

To create a public link, set `share=True` in `launch()`.
User: 彬彬
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/user/base_models/Qwen-7B/web_demo.py", line 125, in predict
    for response in model.chat_stream(tokenizer, _query, history=_task_history, generation_config=config):
  File "/home/user/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1014, in chat_stream
    assert self.generation_config.chat_format == 'chatml', _ERROR_BAD_CHAT_FORMAT
AttributeError: 'GenerationConfig' object has no attribute 'chat_format'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，您的问题我们无法复现出来，请确认您拉取并使用的是我们的最新代码和最新模型，并确定`web_demo.py`中读取generation config的代码未被改动正常执行 https://github.com/QwenLM/Qwen-7B/blob/6f5f076ad13ee0f92976d22b170263b98de3d2ee/web_demo.py#L65-L67

**Comment by yangapku** [comment]
请确认args.checkpoint_path目录下，存在我们在huggingface上官方提供的最新版本[generation_config.json](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/generation_config.json)，以保证读取generation config正常执行

**Comment by JustinLin610** [comment]
应该是代码版本未更新，当前modeling_qwen.py已经没有这个assertion。这部分修改是为了适配最新的int4模型方案。

**Comment by cgq0816** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/42534237/698cac6d-8b1a-4fe1-b746-52486a33eae1)
你好，我这里也遇到这个问题了，我看了一下config路劲不是我加载模型的路径，这个问题该怎么解决呢？

**Comment by cgq0816** [comment]
代码有两处修改：
1、加载的时候需要设置model.generation_config
![image](https://github.com/QwenLM/Qwen-7B/assets/42534237/13c6f7c3-c957-452b-b60e-d899ea6a0fec)
2、预测的时候把generation_config参数去掉
![image](https://github.com/QwenLM/Qwen-7B/assets/42534237/bec0e83f-98c9-45d2-904c-448b524c3e65)
修改完成之后，代码web_demo.py可以跑通

**Comment by mydayun** [comment]
示例有问题，将
response, history = model.chat(tokenizer, "你好", history=None)
添加 generation_config=config解决了
response, history = model.chat(tokenizer, "你好", history=None, generation_config=config)

**Comment by mydayun** [comment]
我也出现了同样的问题，是示例有问题，将
response, history = model.chat(tokenizer, "你好", history=None)
添加 generation_config=config解决了
response, history = model.chat(tokenizer, "你好", history=None, generation_config=config)

**Comment by JustinLin610** [comment]
> 我也出现了同样的问题，是示例有问题，将 response, history = model.chat(tokenizer, "你好", history=None) 添加 generation_config=config解决了 response, history = model.chat(tokenizer, "你好", history=None, generation_config=config)

这个你应该是使用量化模型吧，我们在量化那个章节标明了要传入generation_config=config。如果不是量化模型，则可以使用之前的用法，model.generation_config = xxx 或者generation_config=config这种传参

**Comment by howardgriffin** [comment]
> model.chat(t

不行啊

**Comment by kingdomad** [comment]
我今天下载的模型也遇到这个问题了

**Comment by zhouenxian** [comment]
在官方给出的示例的基础之上加上generation_config即可解决该问题，示例如下:

from transformers import AutoTokenizer,AutoModelForCausalLM
from transformers.generation.utils import GenerationConfig
tokenizer = AutoTokenizer.from_pretrained("/datas/work/zex/checkpoint/Qwen", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    "/datas/work/zex/checkpoint/Qwen",
    device_map="auto",
    trust_remote_code=True
)
eos_token_id = tokenizer.convert_tokens_to_ids(["```"])[0]
model.generation_config = GenerationConfig(
        max_new_tokens=224,
        repetition_penalty=1.2,
        top_p=0.95,
        pad_token_id=eos_token_id,
        # n_sample=20,
        num_beams=5,
        temperature=0.1,
        num_return_sequences=1,
        eos_token_id=eos_token_id,
        output_scores=True,
        use_cache=True
    ).from_pretrained(
        "/datas/work/zex/checkpoint/Qwen"
    )
model = model.eval()
...............
response = model.chat(tokenizer, prompts, history=None)

**Comment by xiaoduozhou** [comment]
我是transformers 版本太低了，导致出现这个bug, 升级transformer 就解决了，      模型里面文件 generation_config.json 配置里面有"transformers_version": "4.36.2" ， 我本地的版本是 4.26 的， 导致配置取不到，升级后解决
