### ISSUE TITLE
翻译英译中评测指标不一致

### ISSUE THREAD

**Issue by YangZhongyi-XJTU** [QwenLM/Qwen-7B#251]
我使用Qwen-7B-chat模型和"将下列语句翻译成中文:"的prompt方式在wmt22 en-zh测试集上测得BLEU score为37.2，远高于readme中的30.6。请问项目中的翻译指标是如何测试的？

**Comment by Losin** [comment]
我们报的指标是Qwen-7B模型的，非chat版，使用的lm-eval-harness 单reference 5-shot的SacrebLEU，没有对prompt做过精细调整
