### ISSUE TITLE
[BUG] 聊天出现很多不相关话题的回答。

### ISSUE THREAD

**Issue by chenchun0629** [QwenLM/Qwen-7B#253]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用text-generation-webui 进行部署，进行聊天出现很多不相关的回答。

其他场景：
- 使用官方web_demo.p部署Qwen-7B-Chat,也是相同情况。
- 使用text-generation-webui 部署其他模型，聊天正常。未出现类似问题。

![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/526e7011-a5ef-4d6c-a5d5-080e0c8f5fa8)
![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/bbb38dac-1a86-447f-b732-64876d5e58ef)
![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/6aa41101-ccdd-479d-9fc1-30f260937d98)

### 复现方法 | Steps To Reproduce

1、使用text-generation-webui 进行部署
```bash
conda create -n textgen python=3.11
conda activate textgen
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
```
2、下载模型
```bash
git lfs install
git clone https://huggingface.co/Qwen/Qwen-7B-Chat
mv Qwen-7B-Chat text-generation-webui/models/
```

3、启动text-generation-webui
```bash
python server.py --model Qwen-7B-Chat  --trust-remote-code
```

### 运行环境 | Environment

```Markdown
- OS:centos7.9
- Python:3.11
- Transformers:4.32.1
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
请尝试看看[这里方法](https://huggingface.co/Qwen/Qwen-7B-Chat/discussions/26#64d306b50f17d186414fe550)能否解决。

`text-generation-webui`的默认配置与Qwen并不兼容，它是看输出字符串看是否有中止字符串来判断中止的，需要设置`skip_special_tokens`为`False`，且配置custom_stopping_strings为`["<|im_end|>", "<|im_start|>", "<|endoftext|>"]`。

**Comment by chenchun0629** [comment]
> 请尝试看看[这里方法](https://huggingface.co/Qwen/Qwen-7B-Chat/discussions/26#64d306b50f17d186414fe550)能否解决。
> 
> `text-generation-webui`的默认配置与Qwen并不兼容，它是看输出字符串看是否有中止字符串来判断中止的，需要设置`skip_special_tokens`为`False`，且配置custom_stopping_strings为`["<|im_end|>", "<|im_start|>", "<|endoftext|>"]`。

你好，根据你所说的设置后，报错了。


![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/587c468d-3e99-4c44-8e25-c41186eedda3)
![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/33b36752-f5ae-4ec3-86c8-6b8262440434)
![image](https://github.com/QwenLM/Qwen-7B/assets/3328490/084026e5-7c0b-4a8e-b483-af55387bc010)

**Comment by chenchun0629** [comment]
修改apply_stopping_strings方法如下，即可修复：
```python

def apply_stopping_strings(reply, all_stop_strings):
    stop_found = False
    for string in all_stop_strings:
        if isinstance(string, list):
            for s in string:
                idx = reply.find(s)
                if idx != -1:
                    reply = reply[:idx]
                    stop_found = True
                    break
        else:
            idx = reply.find(string)
            if idx != -1:
                reply = reply[:idx]
                stop_found = True
                break

    if not stop_found:
        # If something like "\nYo" is generated just before "\nYou:"
        # is completed, trim it
        for string in all_stop_strings:
            if isinstance(string, list):
                for s in string:
                    for j in range(len(s) - 1, 0, -1):
                        if reply[-j:] == string[:j]:
                            reply = reply[:-j]
                            break
                    else:
                        continue
            else:
                for j in range(len(string) - 1, 0, -1):
                    if reply[-j:] == string[:j]:
                        reply = reply[:-j]
                        break
                else:
                    continue

            break

    return reply, stop_found
```
