### ISSUE TITLE
[BUG] <title> GPTQ int4版本 cpu版本报错"addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by invisifire** [QwenLM/Qwen-7B#255]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

利用modelscoup提供的cpu环境部署，安装最新GPTQ cpu版。大概看了一下，应该属于是autoGPTQ那边兼容性的问题，在他们的历史库里也能找到相关报错，作者当时说要修复但是感觉没完全修复。

### 复现方法 | Steps To Reproduce

打开cpu示例
安装autoGPTQ最新版
运行实例代码

### 运行环境 | Environment

```Markdown
modelscoup提供的cpu环境
```

**Comment by JustinLin610** [comment]
GPTQ这个不能用CPU哈
