### ISSUE TITLE
[BUG] <title>微调后的模型无法生成内容

### ISSUE THREAD

**Issue by toufunao** [QwenLM/Qwen-7B#256]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

利用自己的数据集，格式为{"Instruction":"XXX","Input":"XXX","Output":"XXX"}进行lora微调，但是在推理阶段调用model.generate（）方法无法生成内容，并且直接跳出model.generate()所在的函数。

### 运行环境 | Environment

```Markdown
- OS:RHEL7
- Python:3.10.10
- Transformers:4.32.0
- PyTorch:2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by JustinLin610** [comment]
具体使用什么框架finetune，如何finetune？ 另由于涉及三方代码库，一些问题我们可能得相关代码维护者才能解决。

**Comment by toufunao** [comment]
我自行解决完毕，谢谢您的回复。

**Comment by SefaZeng** [comment]
想问下怎么解决的？我这边也有类似的问题。
