### ISSUE TITLE
请问Qwen-7B和Qwen-7B-Chat的微调样本模板格式是什么样的？

### ISSUE THREAD

**Issue by chenchun0629** [QwenLM/Qwen-7B#257]
是有固定格式吗？需要用到`<|im_start|>`、`<|im_end|>`、`<|endoftext|>`隔开吗？

能否提供样本模板格式，参考一下。谢谢！

**Comment by JustinLin610** [comment]
如果自行微调可以自己设计格式，我们的和openai的chatml格式一致[link](https://github.com/openai/openai-python/blob/main/chatml.md)

**Comment by chenchun0629** [comment]
> 如果自行微调可以自己设计格式，我们的和openai的chatml格式一致[link](https://github.com/openai/openai-python/blob/main/chatml.md)

了解
