### ISSUE TITLE
[BUG] 埃塞俄比亚的首都是!

### ISSUE THREAD

**Issue by AnitaSherry** [QwenLM/Qwen-7B#266]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

`2023-09-01 08:07:05.234824: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-01 08:07:05.284335: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-01 08:07:05.982342: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:08<00:00,  1.10s/it]
/home/kemove/anaconda3/envs/sakura/lib/python3.11/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
Input length of input_ids is 39, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
————————————打印后的结果————————————
蒙古国的首都是乌兰巴托（Ulaanbaatar）
冰岛的首都是雷克雅未克（Reykjavik）
埃塞俄比亚的首都是!
`

### 期望行为 | Expected Behavior

埃塞俄比亚的首都是亚的斯亚贝巴（Addis Ababa）

### 复现方法 | Steps To Reproduce

运行Qwen-7B
```
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-7B", trust_remote_code=True)

# 打开bf16精度，A100、H100、RTX3060、RTX3070等显卡建议启用以节省显存
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="auto", trust_remote_code=True, bf16=True).eval()
# 打开fp16精度，V100、P100、T4等显卡建议启用以节省显存
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="auto", trust_remote_code=True, fp16=True).eval()
# 使用CPU进行推理，需要约32GB内存
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="cpu", trust_remote_code=True).eval()
# 默认使用自动模式，根据设备自动选择精度
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B", device_map="auto", trust_remote_code=True).eval()

# 可指定不同的生成长度、top_p等相关超参
model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-7B", trust_remote_code=True)

inputs = tokenizer('蒙古国的首都是乌兰巴托（Ulaanbaatar）\n冰岛的首都是雷克雅未克（Reykjavik）\n埃塞俄比亚的首都是', return_tensors='pt')
inputs = inputs.to(model.device)
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
# 蒙古国的首都是乌兰巴托（Ulaanbaatar）\n冰岛的首都是雷克雅未克（Reykjavik）\n埃塞俄比亚的首都是亚的斯亚贝巴（Addis Ababa）...
```

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 18.04.6 LTS
- Python:3.11.4
- Transformers:4.31.0
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by AnitaSherry** [comment]
只提问埃塞俄比亚的首都是
回答如下：
埃塞俄比亚的首都是!!perfil☧ clearingChristianEntity酷! borderียน.printf gratis

**Comment by JustinLin610** [comment]
如果直接使用，建议用Qwen-7B-Chat模型，Qwen-7B是预训练模型，只支持续写。

我们无法复现你的case，不太确定是不是你们改过什么内容。如下图所示：

![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/7f6c8c1b-3b69-44f5-bb41-8194da2cbc3b)

![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/84d6e123-c24e-4beb-9073-e5be3e70263a)

**Comment by AnitaSherry** [comment]
> 如果直接使用，建议用Qwen-7B-Chat模型，Qwen-7B是预训练模型，只支持续写。
> 
> 我们无法复现你的case，不太确定是不是你们改过什么内容。如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/27664428/264974807-7f6c8c1b-3b69-44f5-bb41-8194da2cbc3b.png)
> 
> ![image](https://user-images.githubusercontent.com/27664428/264974526-84d6e123-c24e-4beb-9073-e5be3e70263a.png)

问题解决了，是因为多卡之间没有共享显存，导致计算错误
