### ISSUE TITLE
有没有大佬提供下MacOS 下 m 系列芯片的使用教程

### ISSUE THREAD

**Issue by zhangvj** [QwenLM/Qwen-7B#27]
纯小白，想尝试下

**Comment by ernestyao** [comment]
你用text-generation-webui加载吧，支持Apple Silicon芯片显卡的

**Comment by JavinYang** [comment]
> 你用text-generation-webui加载吧，支持Apple Silicon芯片显卡的

text-generation-webui是啥？好像只有一个web_demo.py
