### ISSUE TITLE
[BUG] tokenize

### ISSUE THREAD

**Issue by goog** [QwenLM/Qwen-7B#284]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```python
ids = tokenizer.encode("<|im_start|>print('我是一只猫<|extra_0|>')\n#喵喵喵. 然<|im_end|>", 
                       allowed_special={'<|im_start|>', '<|im_end|>', '<|extra_0|>'}, 
                       disallowed_special={'<|endoftext|>'}) + [tokenizer.eod_id]
print("ids:", ids)
tokenizer.convert_ids_to_tokens(ids)
```

the space break the ran(然) utf bytes code

['<|im_start|>',
 b'print',
 b"('",
 b'\xe6\x88\x91',
 b'\xe6\x98\xaf\xe4\xb8\x80',
 b'\xe5\x8f\xaa',
 b'\xe7\x8c\xab',
 '<|extra_0|>',
 b"')\n",
 b'#',
 b'\xe5\x96\xb5',
 b'\xe5\x96\xb5',
 b'\xe5\x96\xb5',
 b'.',
 **b' \xe7',**    
 b'\x84',
 b'\xb6',
 '<|im_end|>',
 '<|endoftext|>']

### 运行环境 | Environment

```Markdown
- OS:linux
- Python:3.10.6
- Transformers:4.33.1
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Hi, goog.

As we are using a plain BPE tokenizer (not the kind involving language models or pursuing minimal tokens), this  behavior is expected.

The tokenizer was trained on the UTF-8 byte sequences and is based solely on byte distribution, meaning it does not have knowledge of which bytes can form a valid UTF-8 codepoint, character or word. This can result in characters being sub-tokenized differently in different contexts, even for English words. For example，
![image](https://github.com/QwenLM/Qwen-7B/assets/17811943/9c121a57-0bc8-47f4-b885-51559f40394b)

This simply suggests that those combinations occur more frequently in the data.

If it is crucial that certain words are tokenized the same regardless of context, you could pre-tokenize the text (e.g., extract the Chinese part) and then concatenate the token ids together.

**Comment by goog** [comment]
got it!   
tiktoken output is same enc.encode("there is one cat. Pandas are doing smth")
