### ISSUE TITLE
[BUG] Wrong field name used in model's config.json

### ISSUE THREAD

**Issue by Yangqing** [QwenLM/Qwen-7B#286]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Hey - just want to flag an issue. In the model `config.json` file, you are using the wrong field name: `tokenizer_type` should actually be `tokenizer_class`, like this line: https://huggingface.co/Qwen/Qwen-7B/blob/main/config.json#L30

This will cause the problem that, if you use `pipeline` to instantiate the model, the model's tokenizer fails to load, and you may encounter errors like:
![Screenshot 2023-09-08 at 1 16 23 AM](https://github.com/QwenLM/Qwen-7B/assets/551151/d61df634-70d4-4723-9737-d5a833a7d359)

### 期望行为 | Expected Behavior

Change the line in models' `config.json`
```
  "tokenizer_type": "QWenTokenizer",
```
to
```
  "tokenizer_class": "QWenTokenizer",
```

### 复现方法 | Steps To Reproduce

Instead of explicitly instantiate the model and tokenizer, use the pipeline interface, like the huggingface default one:
```
from transformers import pipeline
pipe = pipeline("text-generation", model="Qwen/Qwen-7B", trust_remote_code=True)
```

### 运行环境 | Environment

```Markdown
Your typical env will do.
```

### 备注 | Anything else?

Nope. This affects all your models, so consider changing all of them. It's a minor fix though.

Just want to flag this as an old friend. Good luck.

**Comment by fyabc** [comment]
Thank you for your suggestions! We have fixed `config.json` in our HF repo.
