### ISSUE TITLE
官方提供示例调用报未知异常

### ISSUE THREAD

**Issue by AgeFades** [QwenLM/Qwen-7B#30]
<img width="1189" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/45227407/30e0c46b-4e30-4444-9035-34bbf5f6b66d">

**Comment by AgeFades** [comment]
只用官方提供的SDK

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
            <version>2.0.1</version>
        </dependency>
缺少Gson相关类。
加上Gson最新依赖，缺少OkHttp的类。
加上OkHttp最新依赖，就报这个异常。

**Comment by liuyhwangyh** [comment]
您好，请使用maven或者gradle 使用，单独使用会缺少其他依赖包

**Comment by AgeFades** [comment]
> Mavan加上所有报错提示的需要相关依赖包了，现在请求已经发出调通了，只是报500未知异常，我调用端这边没办法排查问题了

**Comment by liuyhwangyh** [comment]
export DASHSCOPE_NETWORK_LOGGING_LEVEL="HEADERS" 日志发出来
