### ISSUE TITLE
用自己的数据集加载，总是报错

### ISSUE THREAD

**Issue by xiaomeng654321** [QwenLM/Qwen-7B#310]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在加载自己的数据集遇到报错：
Loading data...
Traceback (most recent call last):
  File "/data0/yanwei/Qwen-7B-main/finetune.py", line 353, in <module>
    train()
  File "/data0/yanwei/Qwen-7B-main/finetune.py", line 337, in train
    data_module = make_supervised_data_module(
  File "/data0/yanwei/Qwen-7B-main/finetune.py", line 242, in make_supervised_data_module
    train_json = json.load(open(data_args.data_path, "r"), strict=False)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/conda/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 2365465684 (char 2365465683)
1、按照数据集的格式，将LLaMA-Efficient-Tuning训练过的数据集进行转换，成如下的格式：
[
  {
    "id": "identity_0",
    "conversations": [
      {
        "from": "user",
        "value": "你好"
      }
    ]
  }，
 {
    "id": "identity_1",
    "conversations": [
      {
        "from": "user1",
        "value": "你好1"
      }
    ]
  }
]
2、更改finetune.py中，加载数据的代码，按照非严格模式加载：
train_json = json.load(open(data_args.data_path, "r"))
更改为：
train_json = json.load(open(data_args.data_path, "r"), strict=False)

经过上面两步操作后，出现了上面的问题
可以帮忙看下是哪里的问题吗

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by kyriekevin** [comment]
我也不是使用qwen的chatml的数据格式（vicuna的格式），但是是通过修改数据预处理方法来读取数据集
<img width="893" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/61409791/a84bc766-4630-409a-90fb-5eb30e43456d">

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/9b7b0f1c-497c-4d12-93c4-ab3ec21647b3)没有user1。楼上也解释清楚了，如果用fastchat官方一模一样的格式，那就human gpt，我们默认user assistant。只能这俩

**Comment by xiaomeng654321** [comment]
谢谢楼主们~，我改下格式，重新微调
