### ISSUE TITLE
RuntimeError: value cannot be converted to type at::Half without overflow

### ISSUE THREAD

**Issue by trexliu** [QwenLM/Qwen-7B#32]
跑官方README里面的例子和repo中的demo.py都报这个错误。

File "/root/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B-Chat/44e46a0f02169a2c4790fbcccec82cd20f4df717/qwen_generation_utils.py", line 349, in __call__
    scores[i, self.eos_token_id] = float(2**30)
RuntimeError: value cannot be converted to type at::Half without overflow

**Comment by jackaihfia2334** [comment]
+1,求解答

**Comment by shujun1992** [comment]
bf16=True可以解决

**Comment by logicwong** [comment]
@trexliu @jackaihfia2334 感谢反馈！这个原因是float(2**30)超出了float16的范围，最新代码已经修复了哈。可以再尝试下

**Comment by trexliu** [comment]
收到。。可以运行了。。感谢
