### ISSUE TITLE
这就是阿里代码水平？

### ISSUE THREAD

**Issue by makerroot** [QwenLM/Qwen-7B#34]
<img width="841" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/38029854/3e3cf301-d5f0-4100-8578-dc6c91977443">

**Comment by makerroot** [comment]
关键是环境依赖的requirement.txt都没有一个，人才呀。

**Comment by hequan2017** [comment]
路过

**Comment by makerroot** [comment]
> 路过
哈哈哈，看看阿里人的态度，直接close，没理由

**Comment by makerroot** [comment]
阿里人的态度真好，直接close，不说为啥

**Comment by Sug2077** [comment]
> 阿里人的态度真好，直接close，不说为啥

大佬提交个PR教一下

**Comment by makerroot** [comment]
> > 阿里人的态度真好，直接close，不说为啥
> 
> 大佬提交个PR教一下


哈哈，最基本的像print这种只是在调试代码的时候使用，或者debug调试，日志就直接log输出。

**Comment by xuguozhi** [comment]
eval时多打几个print也没毛病吧

**Comment by makerroot** [comment]
> eval时多打几个print也没毛病吧

你们代码都不进行code review的吗
