### ISSUE TITLE
Qwen-7B tokenizer 使用了多少语料训练

### ISSUE THREAD

**Issue by JayLee15** [QwenLM/Qwen-7B#37]
Qwen-7B tokenizer 使用了多少语料训练

**Comment by JustinLin610** [comment]
https://github.com/QwenLM/Qwen-7B/blob/main/tech_memo.md

**Comment by Losin** [comment]
> Qwen-7B tokenizer 使用了多少语料训练

可以参考https://github.com/QwenLM/Qwen-7B/blob/main/tech_memo.md，语料tokens数大于2.2T

**Comment by JayLee15** [comment]
tokenizer的生成也用了全量的语料吗

**Comment by Losin** [comment]
训练tokenizer大概使用了10G这个数量级的数据
