### ISSUE TITLE
Bug of tokenize "<|endoftext|>"

### ISSUE THREAD

**Issue by yangjianxin1** [QwenLM/Qwen-7B#39]
在对"<|endoftext|>"进行tokenize的时候，会将其切分成多个token，而不是151643这一个token。

运行脚本：
```python
tokenizer = AutoTokenizer.from_pretrained('Qwen/Qwen-7B', trust_remote_code=True)
print('encode <|endoftext|>: {}'.format(tokenizer.encode('<|endoftext|>')))
```

分词结果为：
```
encode <|endoftext|>: [27, 91, 8691, 723, 427, 91, 29]
```

希望qwen的同学修复一下。

**Comment by JustinLin610** [comment]
这个是防止被hack eod token的操作，所以encode的时候会把它切碎

**Comment by JustinLin610** [comment]
See #24

**Comment by Sanster** [comment]
要改训练代码，可以参考 `Qwen/Qwen-7B-Chat` 的逻辑加上手动拼 token_ids 的代码，而不能直接把拼接好的完整 prompt 送给 tokenizer。

不过我还是建议 `Qwen/Qwen-7B` 直接去掉 avoid injection attacks 就好了，对于不同训练代码的适用性更高

**Comment by yangjianxin1** [comment]
> 要改训练代码，可以参考 `Qwen/Qwen-7B-Chat` 的逻辑加上手动拼 token_ids 的代码，而不能直接把拼接好的完整 prompt 送给 tokenizer。
> 
> 不过我还是建议 `Qwen/Qwen-7B` 直接去掉 avoid injection attacks 就好了，对于不同训练代码的适用性更高

好的，感谢，解释的很清楚。
我训练的时候，把input_id和eos_token_id做手动拼接；推理时将input和eos_token拼接，然后进行tokenize，发现不一致，所以以为是bug。感谢解答
