### ISSUE TITLE
安装flash-attention装不上 报错

### ISSUE THREAD

**Issue by TuDaCheng** [QwenLM/Qwen-7B#40]
我使用Python3.8/3.10安装这个flash-attention都装不上 报错 Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects，有遇到过这个问题的小伙伴吗

**Comment by logicwong** [comment]
跟#10 类似的问题，可以去[FlashAttention](https://github.com/Dao-AILab/flash-attention)的issue区找一下解法，或者直接提issue给tridao
