### ISSUE TITLE
QWenLMHeadModel.__init__() got an unexpected keyword argument 'use_bf16'

### ISSUE THREAD

**Issue by quan2005** [QwenLM/Qwen-7B#45]
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", trust_remote_code=True, use_bf16=True).eval()

------------------------------------

QWenLMHeadModel.__init__() got an unexpected keyword argument 'use_bf16'

**Comment by logicwong** [comment]
@quan2005 Thanks for pointing this out. It's a typo, `use_bf16=True` should be `bf16=True`. We have update Readme
