### ISSUE TITLE
请问Qwen-7B插件调用那个Agent要怎么用

### ISSUE THREAD

**Issue by TuDaCheng** [QwenLM/Qwen-7B#47]
类似openAI那样的函数调用功能

**Comment by xusenlinzy** [comment]
通过 https://github.com/xusenlinzy/api-for-open-llm 启动模型，然后可以参考 https://github.com/xusenlinzy/api-for-open-llm/blob/master/examples/quad_calculator.py 调用工具

**Comment by yhfgyyf** [comment]
> 通过 https://github.com/xusenlinzy/api-for-open-llm 启动模型，然后可以参考 https://github.com/xusenlinzy/api-for-open-llm/blob/master/examples/quad_calculator.py 调用工具

能否修改下function call的代码，能让langchain的agent支持function call调用

**Comment by JianxinMa** [comment]
langchain 库提供了一些现成的工具实现，qwen 可以直接调用那些工具。关于如何让 qwen  使用 langchain 实现的工具，可以见这个示例：https://github.com/QwenLM/Qwen-7B/blob/main/examples/langchain_tooluse.ipynb
