### ISSUE TITLE
qwen7b的硬件需求是什么呀？

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen-7B#52]
请问有公布模型训练和测评的硬件需求吗？需要调研硬件资源需求，但是md文件好像没有明确说明，大家有看到嘛？

**Comment by zhangyichang** [comment]
你好，目前有推断的硬件资源需求，https://github.com/QwenLM/Qwen-7B#quantization 


Precision | MMLU | Memory
-- | -- | --
BF16 | 56.7 | 16.2G
Int8 | 52.8 | 10.1G
NF4 | 48.9 | 7.4G

训练的硬件需求我们会后续更新。

**Comment by BeastyZ** [comment]
我是A40 48G 显存，采用官方默认的加载精度(fp32)，显存占用31G左右。

**Comment by txy6666yr** [comment]
> 你好，目前有推断的硬件资源需求，https://github.com/QwenLM/Qwen-7B#quantization
> 
> Precision	MMLU	Memory
> BF16	56.7	16.2G
> Int8	52.8	10.1G
> NF4	48.9	7.4G
> 训练的硬件需求我们会后续更新。
好的 谢谢

**Comment by txy6666yr** [comment]
> 我是A40 48G 显存，采用官方默认的加载精度(fp32)，显存占用31G左右。

好的，我算力不够，第一天量化int8加载报错，我今天改成fp16再试试

**Comment by CN-COTER** [comment]
> 你好，目前有推断的硬件资源需求，https://github.com/QwenLM/Qwen-7B#quantization
> 
> Precision	MMLU	Memory
> BF16	56.7	16.2G
> Int8	52.8	10.1G
> NF4	48.9	7.4G
> 训练的硬件需求我们会后续更新。

您好，请问能提供一个int8的Qwen-chat-7B下载链接吗？

**Comment by CN-COTER** [comment]
> > 你好，目前有推断的硬件资源需求，https://github.com/QwenLM/Qwen-7B#quantization
> > Precision	MMLU	Memory
> > BF16	56.7	16.2G
> > Int8	52.8	10.1G
> > NF4	48.9	7.4G
> > 训练的硬件需求我们会后续更新。
> 
> 您好，请问能提供一个int8的Qwen-chat-7B下载链接吗？

我看了一下Quant用的是AutoGPTQ，如果不方便提供int8的模型的话，可以提供一下GPTQ量化时使用到的datasets吗？
