### ISSUE TITLE
有没有啥微信群啥的，交流交流

### ISSUE THREAD

**Issue by qihangf** [QwenLM/Qwen-7B#54]

**Comment by lucasjinreal** [comment]
![56673f90be6e60c873305a8b07f4cb6](https://github.com/QwenLM/Qwen-7B/assets/21303438/4f273952-265e-4ecb-9a3c-e6073a5c0b62)

**Comment by lucasjinreal** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/21303438/26996c9c-15c7-4085-96a8-2dfbcf5ce17c)

**Comment by You-Know-Who-Z** [comment]
群大于200人了，还有其他群吗

**Comment by wilderchan000** [comment]
> 群大于200人了，还有其他群吗

![image](https://github.com/QwenLM/Qwen-7B/assets/129088930/e9beeee5-380e-4465-bfc5-55f786e89e82)

**Comment by wilderchan000** [comment]
满人了，可以添加微信进群：
![image](https://github.com/QwenLM/Qwen-7B/assets/129088930/ce58893e-9937-4cbb-ab5c-fb1e96b3e399)
