### ISSUE TITLE
通义千问微信交流群

### ISSUE THREAD

**Issue by wilderchan000** [QwenLM/Qwen-7B#58]
![image](https://github.com/QwenLM/Qwen-7B/assets/129088930/6267b6cc-7d77-46ee-9bb9-cc4b1c6abad5)

**Comment by wilderchan000** [comment]
满人了，需要的话加微信入群呗：
![image](https://github.com/QwenLM/Qwen-7B/assets/129088930/96a0c09d-ea7f-4daa-b059-fd6a0ffcdde4)

**Comment by yangapku** [comment]
大家可以从最新readme，找到我们官方微信二维码，进入通义千问官方交流群哈~ 这个repo就先关闭了

**Comment by sunyclj** [comment]
> 满人了，需要的话加微信入群呗： ![image](https://user-images.githubusercontent.com/129088930/259688194-96a0c09d-ea7f-4daa-b059-fd6a0ffcdde4.png)

这是个人微信吗？加了没回应呢？

**Comment by coding-today** [comment]
readme中的二维码扫描提示群满了。。
