### ISSUE TITLE
tokenizer allowed_special没生效

### ISSUE THREAD

**Issue by MaxMys** [QwenLM/Qwen-7B#59]
![image](https://github.com/QwenLM/Qwen-7B/assets/2140087/5bbf5db1-ae17-4422-9b95-98db122a3115)

**Comment by JustinLin610** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/27664428/6a12d065-b6ab-481f-937a-0eb54db844be)
我这边测试ok的，你看下代码有没更新？

**Comment by gumanchang** [comment]
我也报错，今天早上拉的模型和配置
File "/root/anaconda3/envs/torch2.0/lib/python3.8/site-packages/tiktoken/core.py", line 351, in raise_disallowed_special_token
raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|im_start|>'.
If you want this text to be encoded as a special token, pass it to allowed_special, e.g. allowed_special={'<|im_start|>', ...}.
If you want this text to be encoded as normal text, disable the check for this token by passing disallowed_special=(enc.special_tokens_set - {'<|im_start|>'}).
To disable this check for all special tokens, pass disallowed_special=().

**Comment by MaxMys** [comment]
明天我试试，今天早上更新的，可能是中间版本

**Comment by MaxMys** [comment]
ok
