### ISSUE TITLE
提供 QWen-7B / QWen-7B-Chat 在 OpenCompass 榜单上的评测结果

### ISSUE THREAD

**Issue by Leymore** [QwenLM/Qwen-7B#61]
https://opencompass.org.cn/leaderboard-llm

![image](https://github.com/QwenLM/Qwen-7B/assets/17680578/4cc78869-92df-439d-8e46-8d37f9d84f60)

可以明显看出通义千问这一版模型的性能非常强劲 👍🏻👍🏻👍🏻

**Comment by tonysy** [comment]
All results could be reproduced with OpenCompass. 
- Welcome to https://github.com/internLM/OpenCompass/ for model evaluation

**Comment by vansin** [comment]
理解能力突出
知识能力偏弱

![image](https://github.com/QwenLM/Qwen-7B/assets/25839884/2c184a74-5bfb-4be8-83e7-728ffd15bb1c)

**Comment by Losin** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/19410839/2003ba9b-d02a-4de8-a1fb-7369f9256935)
看了下知识能力偏弱主要是因为NQ和TrivialQA两个任务比较异常，是不是任务输入过长导致模型2048的长度没法conver，所以没能正确输出结果导致的？

**Comment by Losin** [comment]
> 理解能力突出 知识能力偏弱
> 
> https://opencompass.org.cn/model-detail/Qwen-7B
> 
> ![image](https://user-images.githubusercontent.com/25839884/258419624-2c184a74-5bfb-4be8-83e7-728ffd15bb1c.png)

![image](https://github.com/QwenLM/Qwen-7B/assets/19410839/2003ba9b-d02a-4de8-a1fb-7369f9256935)
看了下知识能力偏弱主要是因为NQ和TrivialQA两个任务比较异常，可能没有被正确测试，可以再看看原因

**Comment by Nipi64310** [comment]
> @Leymore @tonysy @vansin 非常感谢评测！NQ和TrivialQA异常的原因应该是较早版本的代码没有打开`use_dynamic_ntk`和`use_logn_attn`引起的，所以千问的实际效果还要超过现在榜上的水平。。。
> 
> 我们内部简单测了一下这两个任务，结果如下（配合上window_attention效果更好）： ![lQLPJxH0b0U42HzNAR7NBmCwH2M22n6ss9UEwgjlm0DpAA_1632_286](https://user-images.githubusercontent.com/36780733/258495068-cc7e1bdc-afcd-4568-ba27-ee3d01a2838c.png)

Hi @logicwong ,
请问下window attention是指这个工作，没在代码里面看到 ？
 https://spaces.ac.cn/archives/9708

**Comment by logicwong** [comment]
@Nipi64310 指的是这个https://github.com/lucidrains/local-attention。window attention不能直接用FlashAttention去实现，我们内部也还在实验window attention与NTK，logn三者的结合，待方法完善之后代码就会release。

**Comment by Leymore** [comment]
跟 @logicwong 私下交流了。说明一下相关情况。
@logicwong 所使用的 TriviaQA 和 NaturalQuestions 是 [LongBench](https://github.com/THUDM/LongBench/tree/main) 中的 TriviaQA 和 NQ，这是由 LongBench 自造的数据集，有上下文文本信息，每个测试用例有 2k ~ 5k 个 token，200  条测试用例。
OpenCompass 所使用的 TriviaQA 和 NaturalQuestions 是原生的数据集，无上下文，仅有问题和答案，每个测试用例 <100 个 token，5k ~ 8k 条测试用例。
两个数据集完全不同，其指标没有可比性。但之前 OpenCompass 测得的结果确实有问题：QWen-7B 在补全时输出的空格导致 OpenCompass 的后处理错误。目前该问题已修复。

OpenCompass 测出来的指标具体如下，网页上汇报的是 0-shot 的结果，已更新完毕：

<img width="403" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/17680578/d1faf8d5-6073-4c9b-b491-c053870c8b1e">
