### ISSUE TITLE
这个是错字吗

### ISSUE THREAD

**Issue by KylinShinlyLin** [QwenLM/Qwen-7B#64]
<img width="683" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/17798310/ba12f9b2-2a3b-4cb7-9ded-4c16f1d97927">

**Comment by JianxinMa** [comment]
是的，感谢提醒。原意是“我说啥你做啥”的，本来想改，但犯懒了，正好测试模型对于用户打错字的反应如何。:)
