### ISSUE TITLE
程序总是崩溃Try importing flash-attention for faster inference...

### ISSUE THREAD

**Issue by yanmengxiang1** [QwenLM/Qwen-7B#65]
按照readme正常安装了flash-attention1.0.8等依赖，gpu是A10的24G，pytorch是2.0.1+cuda117
运行： python demo.py --checkpoint-path='/data/model/Qwen-7B-Chat'
错误：load tokenizer
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...

程序一直崩溃。试了换bf16/fp16/fp32都不行。有人遇到这个问题吗？或者怎么跳过加载flash-attention这一步啊？谢谢

**Comment by logicwong** [comment]
@yanmengxiang123456899 感觉不是flash-attention的问题，你可以先试试在`AutoModelForCausalLM.from_pretrained`里把`use_flash_attn`设成False

**Comment by yanmengxiang123456899** [comment]
@logicwong 你好，我试了use_flash_attn设成False不行。我感觉可能需要把pytorch_model.bin切分多个分开加载，请问您那边有切分的001.bin、002.bin这种文件吗

**Comment by logicwong** [comment]
@yanmengxiang123456899 请问你的模型已经下载到本地了吗？如果是加载阶段报错，你可以先试下把pytorch_model.bin转成bf16精度保存，然后再进行加载？

**Comment by cell-lives** [comment]
> @logicwong 你好，我试了use_flash_attn设成False不行。我感觉可能需要把pytorch_model.bin切分多个分开加载，请问您那边有切分的001.bin、002.bin这种文件吗

好像是内存不够用，大概需要 20G 的内存，你的显存应该是够用的。我的配置是 2080ti（11G），给 WSL 分配 20G 内存就能跑起来文档中的例子。

这是我的测试脚本：

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
from transformers import BitsAndBytesConfig
import torch

# Note: our tokenizer rejects attacks and so that you cannot input special tokens like <|endoftext|> or it will throw an error.
# To remove the strategy, you can add `allowed_special`, which accepts the string "all" or a `set` of special tokens.
# For example: tokens = tokenizer(text, allowed_special="all")
tokenizer = AutoTokenizer.from_pretrained("./Qwen-7B-Chat", trust_remote_code=True)

# quantization configuration for NF4 (4 bits)
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_compute_dtype=torch.bfloat16
)

print("AutoModelForCausalLM ...")
model = AutoModelForCausalLM.from_pretrained(
    "./Qwen-7B", 
    device_map="cuda:0",
    quantization_config=quantization_config,
    trust_remote_code=True,
    use_flash_attn=False
).eval()

print("GenerationConfig ...")
model.generation_config = GenerationConfig.from_pretrained("./Qwen-7B", trust_remote_code=True) # 可指定不同的生成长度、top_p等相关超参

inputs = tokenizer('蒙古国的首都是乌兰巴托（Ulaanbaatar）\n冰岛的首都是雷克雅未克（Reykjavik）\n埃塞俄比亚的首都是', return_tensors='pt')
inputs = inputs.to('cuda:0')
pred = model.generate(**inputs)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

**Comment by mougua** [comment]
我一开始一直oom被killed，后来加大swap就好了
