### ISSUE TITLE
文件`README.md`与`README_CN.md`中关于“开源”的描述与项目的授权协议（LICENSE）中所列出的权利及限制不符

### ISSUE THREAD

**Issue by nirui** [QwenLM/Qwen-7B#67]
只是一个文档上的小问题。

项目文件[`README.md`]与[`README_CN.md`]中均列有“开源”（或"opensource"）的陈述。但“开源”（及"opensource"）是一个术语，有特定定义。[`LICENSE`]文件中所列出的权利及限制并不符合[The Open Source Definition]中给出的定义。具体的冲突条款有：

[`README.md`]: https://github.com/QwenLM/Qwen-7B/blob/a626f56bd68b53ebae445aae29eee9abceb6cfe9/README.md
[`README_CN.md`]: https://github.com/QwenLM/Qwen-7B/blob/a626f56bd68b53ebae445aae29eee9abceb6cfe9/README_CN.md
[`LICENSE`]: https://github.com/QwenLM/Qwen-7B/blob/a626f56bd68b53ebae445aae29eee9abceb6cfe9/LICENSE

> [4. Restrictions]
> If you are commercially using the Materials, and your product or service has more than 100 million monthly active users, You shall request a license from Us. You cannot exercise your rights under this Agreement without our express authorization.

[The Open Source Definition]: https://opensource.org/osd/
[4. Restrictions]: https://github.com/QwenLM/Qwen-7B/blob/a626f56bd68b53ebae445aae29eee9abceb6cfe9/LICENSE#L28

根据[The Open Source Definition]中的定义，一个开源协议应该：

> 6. No Discrimination Against Fields of Endeavor
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

而“If you are commercially using the Materials”以及“and your product or service has more than 100 million monthly active users”均属于“Discrimination Against Fields of Endeavor”。

同时，除非“You shall request a license from Us”中的“license”指的就是[`LICENSE`]文件中所列出的协议本身，则该条款与

> 7. Distribution of License
> The rights attached to the program must apply to all to whom the program is redistributed without the need for execution of an additional license by those parties.

的定义也不一致。

考虑到“开源软件”（"Open Source software"）是指在开源协议下分发的软件，而[`LICENSE`]所载内容并非开源协议，因此该软件并非开源软件，所以使用“开源”（或"opensource"）对其进行表述并不准确。

根据上述事实，建议可以：
1. 将[`README.md`]中的陈述由
   “We opensource Qwen-7B and Qwen-7B-Chat”
   改为
   “We've *published* Qwen-7B and Qwen-7B-Chat”；
3. 同时将[`README_CN.md`]中的陈述由
   “我们在🤖 ModelScope以及hugs Hugging Face均开源了Qwen-7B系列模型。”
   改为
   “我们在🤖 ModelScope以及hugs Hugging Face均*发布*了Qwen-7B系列模型。”。

**Comment by jexjws** [comment]
啊？就这样close了？

我认为滥用"opensource"一词对ChatRWKV这种大模型是不公平的。
