### ISSUE TITLE
给Qwen-7B-Chat套了个ChatGPT的壳，也兼容部分OpenAI接口

### ISSUE THREAD

**Issue by huajianmao** [QwenLM/Qwen-7B#70]
我们在做一个OpenAI兼容接口的小项目。[OpenAI.mini](https://github.com/llmapp/openai.mini)

主要是两个方面的功能：
1. 用各种开源模型实现兼容OpenAI的各个接口，目前支持`chat`的stream和非stream模式、embedding、图片生成、语音转文字、文件上传下载等，具体实现进度可以看[这里](https://github.com/llmapp/openai.mini#status)，部分接口还在实现中。
2. 提供了一个简单的Web前端，这个前端是克隆的ChatGPT官网风格，消息进在本地浏览器的LocalStorage中存储。<ins>**web前端的代码暂时未集成到openai.mini中。不过在v0.0.1的release中已经集成了编译好的前端。**</ins>

具体使用可以看release中的[使用说明](https://github.com/llmapp/openai.mini/releases)。
<h2>注意：如果需要前端功能，请从release中下载，代码库中尚未提供前端代码，release中已经编译集成好了，具体使用方式请看使用说明。</h2>

本人主业不搞机器学习方向，纯兴趣，另外，由于前期也没有写过太多Python代码，所以代码应该有很多bug，欢迎大家帮忙提bug，帮忙改进，欢迎大家star加星，持续批评指正。
计划逐步添加功能，下一步前端代码功能基本完善以后，也会开源。

项目参考了很多大佬的代码，例如 @xusenlinzy 大佬的[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm/), @hiyouga 大佬的[LLaMA-Efficient-Tuning](https://github.com/hiyouga/LLaMA-Efficient-Tuning) 等，表示感谢。

![image](https://github.com/QwenLM/Qwen-7B/assets/1352072/9950fea6-2eee-46b0-9047-652df2a8bea2)
![image](https://github.com/QwenLM/Qwen-7B/assets/1352072/2f2310bc-0b16-413c-8f20-3643fbc5b404)

除了通义千问外，也兼容了几个常见的开源模型，包括百川、ChatGLM、LLaMA2等。

**Comment by pepsigold** [comment]
哈哈，前端泰酷辣，可以写个api吗？谢谢！

**Comment by huajianmao** [comment]
> 哈哈，前端泰酷辣，可以写个api吗？谢谢！

您指的api是哪方面的？😂
前端再整理整理下一步也会开源。

**Comment by pepsigold** [comment]
> > 哈哈，前端泰酷辣，可以写个api吗？谢谢！
> 
> 您指的api是哪方面的？😂 前端再整理整理下一步也会开源。

就是指的支持直接对接本地部署的千问、glm，有的自带api。有的没有api，。

**Comment by huajianmao** [comment]
> > > 哈哈，前端泰酷辣，可以写个api吗？谢谢！
> > 
> > 
> > 您指的api是哪方面的？😂 前端再整理整理下一步也会开源。
> 
> 就是指的支持直接对接本地部署的千问、glm，有的自带api。有的没有api，。 具体可以参照 https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py

[OpenAI.mini](https://github.com/llmapp/openai.mini)本身就支持OpenAI格式的API的。
直接启动服务，然后就可以了。

``` python
import openai

openai.api_base = "http://localhost:8000/api/v1"
openai.api_key = "none"

for chunk in openai.ChatCompletion.create(
    model="Baichuan-13B-Chat",
    messages=[{"role": "user", "content": "Which moutain is the second highest one in the world?"}],
    stream=True
):
    if hasattr(chunk.choices[0].delta, "content"):
        print(chunk.choices[0].delta.content, end="", flush=True)
```

您是希望有一个单一的文件？这个看官方有没有这个想法呗。哈哈。
