### ISSUE TITLE
请支持chat接口更多的参数设置能力

### ISSUE THREAD

**Issue by huajianmao** [QwenLM/Qwen-7B#71]
目前`model.chat`接口仅支持 `tokenizer`, `query`, `history`, `system`, `append_history`, `stream`等参数的支持，
但缺少`max_length`, `do_sample`, `top_p`, `temperature`, `stop_words_ids` ... 等常用参数的支持，建议添加`**kwargs`参数支持。
@JustinLin610

**Comment by huajianmao** [comment]
比如，现在想用[ReAct Prompting 示例](https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_prompt.md)来实现插件调用能力的时候，现在只能单独用generate接口来实现。

(从示例里提供的截图来看，示例好像是使用没有设置stop words的chat接口来实现的？所以没有在`Observation: `的时候停止？)

**Comment by JianxinMa** [comment]
您好，文档和代码已更新，请参考 https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_prompt.md 末尾的FAQ~

**Comment by huajianmao** [comment]
赞，你们太神速了！👍🏻
