### ISSUE TITLE
cli_demo.py 报错TypeError: QWenLMHeadModel.chat() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by caowenhero** [QwenLM/Qwen-7B#72]
`TypeError:` QWenLMHeadModel.chat() got an unexpected keyword argument 'stream'
去掉第48行的'''stream=True'''可运行，但
问第二个问题报错
"""
ValueError: Input [('你为什么要开源', '我是一个大型语言模型，我的目标是为用户提供最好的服务。开源可以让我更好地服务于用户，因为开源意味着更多的用户可以访问我的代码，并对我的工作进行改进和贡献。此外，开源也可以促进我的学习和发展，因为我会不断地收到用户的反馈和建议，从而改进自己的性能和能力。'), ('你为什么要开源', [...])] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.
"""

**Comment by huajianmao** [comment]
模型没有更新吧？stream是昨天开始支持的
