### ISSUE TITLE
[BUG] Syntax error: "(" unexpected"

### ISSUE THREAD

**Issue by Sandraven0** [QwenLM/Qwen-7B#767]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

find this when using the data generated by myself according to the format on github main. Is this error caused by my wrong data format? If so, could the team please offer some example data? 
TypeError: list indices must be integers or slices, not str
  0%|                                                                                                                                                                           | 0/40 [00:00<?, ?it/s]

### 期望行为 | Expected Behavior

correctlly executed the .sh file

### 复现方法 | Steps To Reproduce

Previous steps were done following the instruction, given "sh finetune/finetune_qlora_single_gpu.sh" return "finetune/finetune_qlora_single_gpu.sh: 10: Syntax error: "(" unexpected"
To execute this sh file:
(bash) bash finetune/finetune_qlora_single_gpu.sh

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
根据报错，您需要用bash等支持bash function的shell来运行脚本哈，不能用sh
