### ISSUE TITLE
关于 Qwen-7B tokenizer avoid injection attacks 的疑问

### ISSUE THREAD

**Issue by Sanster** [QwenLM/Qwen-7B#8]
感谢开源预训练模型，试了下 chat 模型的效果感觉很强，正在尝试调优，在集成过程中发现   `Qwen/Qwen-7B`  的 tokenizer 中也实现了 avoid injection attacks 的功能，这个对于非 chat 模型来说应该是不需要的吧？

BTW: warning  中有一处 "OpenAI" 字样未修改：https://huggingface.co/Qwen/Qwen-7B/blob/65b57b1a586a38c959e91bb9dd5fc37cdb5c86fa/tokenization_qwen.py#L156

**Comment by yangapku** [comment]
您好，确实目前avoid injection attacks主要体现在我们对chatml格式中特殊分隔token（im_start、im_end）的处理机制上，这部分逻辑是预训练涉及不到的，应该也不会对目前的预训练生成造成干扰。对于您提出的具体问题，我们已经去除相关描述哈。

**Comment by Sanster** [comment]
嗯，预训练生成没影响。可能有一点点🤏不方便的地方在于，如果想使用 chatml 格式对 `Qwen/Qwen-7B` 进行 SFT 训练，在有 avoid injection attacks 的情况下，为了让 `<im_start>` 是一个 token，训练代码中就要加上就要手动拼 token_ids 的代码，而不能直接把拼接好的完整 prompt 送给 tokenizer。不过问题不大，了解了机制训练代码对应改一下就好了
