### ISSUE TITLE
预训练数据集会开源吗？[Over 2.2 trillion tokens]

### ISSUE THREAD

**Issue by juyongjiang** [QwenLM/Qwen-7B#81]
您好，请问下，”large-scale high-quality dataset of over 2.2 trillion tokens“ 预训练数据集后续会开源吗？
这样，整个开源社区，都可以各取自己所需的数据或者过滤出更高质量的数据来进行更多大(小)模型训练的尝试。: )

**Comment by yuanzyyy** [comment]
同问这个问题，或者预训练数据集都大概使用了哪些呢？不知道后续有没有更详细的说明 @yangapku

**Comment by JustinLin610** [comment]
暂无计划开源这部分数据

**Comment by yuanzyyy** [comment]
那对数据的更进一步说明有计划嘛？

**Comment by pkugyf** [comment]
> 暂无计划开源这部分数据

请问做微调得到chat的过程中用到的开源指令微调数据集有哪些？

**Comment by yuanzyyy** [comment]
@JustinLin610 请问有对数据的更进一步说明计划嘛？（不公开数据集仅说明）

**Comment by SilenceWinter** [comment]
> @JustinLin610 请问有对数据的更进一步说明计划嘛？（不公开数据集仅说明）

附议， 期待能有进一步的数据说明
