### ISSUE TITLE
base模型疑问

### ISSUE THREAD

**Issue by mx8435** [QwenLM/Qwen-7B#84]
hi， 请问Qwen-7B是否有用监督数据？还是只用了无监督语料？

**Comment by GanjinZero** [comment]
For math reasoning, we include RFT data from [gsm8k-ScRel](https://github.com/OFA-Sys/gsm8k-ScRel).

**Comment by GanjinZero** [comment]
Gsm8k is a supervised data source.

**Comment by mx8435** [comment]
> Gsm8k is a supervised data source.

这是用在预训练里面的吗？还是SFT

**Comment by GanjinZero** [comment]
> > Gsm8k is a supervised data source.
> 
> 
> 
> 这是用在预训练里面的吗？还是SFT

pretrain
