### ISSUE TITLE
[HELP] 怎么设置温度，top_p参数

### ISSUE THREAD

**Issue by bh4ffu** [QwenLM/Qwen-7B#85]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

不能设置温度，top_p参数

### 期望行为 | Expected Behavior

设置温度，top_p参数

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

怎么设置温度，top_p参数

**Comment by fyabc** [comment]
有几种设置temperature和top_p的方法：

1. 在`generate()`或`chat()`接口中直接传入相应的参数，如`model.generate(..., top_p=0.5)`等
2. 调用前修改`model.generation.config`，如`model.generation_config.top_p = 0.5`等

QWen-7B的generate逻辑与HuggingFace基本保持一致，更多请参考[官方文档](https://huggingface.co/docs/transformers/main/generation_strategies#customize-text-generation)。

**Comment by bh4ffu** [comment]
thanks， let me try...
