### ISSUE TITLE
[BUG] TypeError: QWenLMHeadModel.chat() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by ZhengHui-Z** [QwenLM/Qwen-7B#87]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

官方给的例子中，chat方法不支持流失

TypeError: QWenLMHeadModel.chat() got an unexpected keyword argument 'stream'

### 期望行为 | Expected Behavior

cli_demo.py无法正常运行

### 复现方法 | Steps To Reproduce

python cli_demo.py

### 运行环境 | Environment

```Markdown
- OS:Ubuntu20.04
- Python:3.10
- Transformers:
- PyTorch:2.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by fyabc** [comment]
model.chat()的stream参数是8月4号开始支持的，可能是您下载的HF模型版本较老的原因，您可以尝试下载最新的HF模型后再重试。

**Comment by ZhengHui-Z** [comment]
> 

感谢，更新代码已解决
