### ISSUE TITLE
[BUG] <huggingface下程序demo运行报错ZeroDivisionError>

### ISSUE THREAD

**Issue by fun0313** [QwenLM/Qwen-7B#89]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[14], line 16
      7 tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen-7B-Chat", trust_remote_code=True)
      9 # use bf16
     10 # model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
     11 # use fp16
   (...)
     14 # model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="cpu", trust_remote_code=True).eval()
     15 # use auto mode, automatically select precision based on the device.
---> 16 model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
     18 # Specify hyperparameters for generation
     19 model.generation_config = GenerationConfig.from_pretrained("Qwen/Qwen-7B-Chat", trust_remote_code=True) # 可指定不同的生成长度、top_p等相关超参

File [d:\environment\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py:488](file:///D:/environment/anaconda3/lib/site-packages/transformers/models/auto/auto_factory.py:488), in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    486     else:
    487         cls.register(config.__class__, model_class, exist_ok=True)
--> 488     return model_class.from_pretrained(
    489         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    490     )
    491 elif type(config) in cls._model_mapping.keys():
    492     model_class = _get_model_class(config, cls._model_mapping)

File [d:\environment\anaconda3\lib\site-packages\transformers\modeling_utils.py:2824](file:///D:/environment/anaconda3/lib/site-packages/transformers/modeling_utils.py:2824), in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2819     logger.warn(
...
    758 # - the size of no split block (if applicable)
    759 # - the mean of the layer sizes
    760 if no_split_module_classes is None:

ZeroDivisionError: float floor division by zero

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，请您再详细填写下"复现方法 | Steps To Reproduce"部分和"运行环境 | Environment"部分，便于我们重现下错误并进行排查哈。
