### ISSUE TITLE
[BUG] 首页md文档/Performance 一节链接无法访问

### ISSUE THREAD

**Issue by forrest1g** [QwenLM/Qwen-7B#90]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

链接：https://github.com/QwenLM/Qwen-7B/blob/main/techmemo-draft.md  返回404

### 期望行为 | Expected Behavior

链接到有效文档上。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，感谢您的指出！我们已经再中英文readme中修复了正确的链接~欢迎您继续提出宝贵的意见！
