### ISSUE TITLE
[HELP] 嵌入式知识问答，当问题在提供的上下文中不能找到答案时，模型会自己组织语言生成答案，这种问题怎么有效的优化呢，大家有没有思路？

### ISSUE THREAD

**Issue by bh4ffu** [QwenLM/Qwen-7B#91]
PROMPT如下：
基于以下上下文，回答用户的问题。如果无法从中得到答案，请说 “抱歉，我不清楚”，不允许编造，请使用中文。
上下文：
清华大学在北京
南京大学在南京
问题：阿里巴巴在哪里？

问答截图如下：
![image](https://github.com/QwenLM/Qwen-7B/assets/113177453/4c6306de-ad45-4a05-99b2-ce361f2323fc)

**Comment by xunki** [comment]
我也遇到了类似的问题，我参考了 [阿里云的demo](https://help.aliyun.com/document_detail/2357332.html) 和 [quivr](https://github.com/StanGirard/quivr/blob/main/backend/core/llm/prompts/LANGUAGE_PROMPT.py) 的 prompt，也试了国内几个公开的大模型或API，效果均不理想。

从 ceval 榜单上看，已经有很多模型的中文能力超越 ChatGPT，一轮测试下来还是 ChatGPT 是最可靠及稳定的，也许是因为 ChatGPT 的 RHLF 做的更好，从目前大模型无法完全避免知识幻觉的问题考虑，通过强化逻辑能力再结合文本向量搜索的方案，可能更具有应用价值。

一些拙见，也是希望国内的中文大模型越来越强。

**Comment by valkryhx** [comment]
ceval刷榜不一定说明效果就好  刷榜和实际效果 大家都懂

**Comment by HongyuJiang** [comment]
查知识库返回结果小于1条的时候，返回固定的内容是不是就可以了？

**Comment by HongyuJiang** [comment]
查知识库的时候，设置一个相似度阈值，如果筛选后的结果小于一条，就返回固定内容，不知道这样可不可以？

**Comment by Nipi64310** [comment]
mark

**Comment by JianxinMa** [comment]
您好，“阿里巴巴在哪里？”这个问题可能是因为 overfit 我司数据了，导致很难做出效果。我换了个别的问题，比如“中山大学哪里？”，然后通过 **提供参考示例（in-context examples）** 的方式，可以在一定程度上让模型学会说“抱歉，我不知道”。

比如，在 https://modelscope.cn/studios/qwen/Qwen-7B-Chat-Demo/summary 的 qwen-7b demo 上，当我输入如下 prompt （包含两个前置的参考示例）时，模型会回答不知道：

输入：
```
基于以下上下文，回答用户的问题。如果无法从中得到答案，请说 “抱歉，我不清楚”，不允许编造，请使用中文。
上下文：
人民币汇率又创新高，已经是10年来峰值。
问题：人民币汇率多少？
回答：抱歉，我不清楚。

基于以下上下文，回答用户的问题。如果无法从中得到答案，请说 “抱歉，我不清楚”，不允许编造，请使用中文。
上下文：
当然是清华更厉害。
北大不堪一击。
问题：清华北大哪家强？
回答：清华。

基于以下上下文，回答用户的问题。如果无法从中得到答案，请说 “抱歉，我不清楚”，不允许编造，请使用中文。
上下文：
清华大学在北京
南京大学在南京
问题：中山大学哪里？
回答：
```

qwen-7b 输出：
```
抱歉，我不清楚。
```

作为对比，如果不提供 prompt 开头的两个参考示例，则模型会自信地说出“中山大学在广州”。
