### ISSUE TITLE
[BUG] 关于流式接口返回乱码的一点探索

### ISSUE THREAD

**Issue by ZhengHui-Z** [QwenLM/Qwen-7B#92]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

流失接口在返回空格的时候会出现乱码字符

乱码token编号：51461

<img width="1032" alt="image" src="https://github.com/QwenLM/Qwen-7B/assets/13689856/99f79071-5501-426e-9fef-84caa3b545f5">

```python
tokenizer.decode([13, 51461], skip_special_tokens=True), tokenizer.decode([13, 51461, 117], skip_special_tokens=True)
```
51461是空格字符，但是出现在结尾会变成�，后面有接其他字符就恢复正常，目前还在检查产生原因。

### 期望行为 | Expected Behavior

不会产生乱码

### 复现方法 | Steps To Reproduce

官方stream demo，但是需要执行打印出每一次流式返回结果：

```python
for response in model.chat(tokenizer, prompt, history=history, stream=True):
    print(response)
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu21.04
- Python:3.10
- Transformers:
  - sentence-transformers         2.2.2
  - transformers                  4.30.2
  - transformers-stream-generator 0.0.4
- PyTorch:2.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by JianxinMa** [comment]
您好，这不是bug，是tokenizer的原理导致 —— 单个 token 并不一定对应任何字词，有时候需要多个 tokens 组合才能构成合法的字词 —— 因此会出现您观察到的 “后面有接其他字符就恢复正常” 现象。如果完全生成结束后，依然有乱码，才是 bug。

一种较简单的解决方法就是在未完全生成结束前，先简单过滤掉 response 末尾的非法字符。

**Comment by ZhengHui-Z** [comment]
是的，后面确认了一下，tokenizer使用的是byte编码方式，流失会导致结尾出现非法字符

b' Primitive' 51460
b' \xe6\xa0' 51461
b'.Character' 51462
b'\xe8\xa1\xa8\xe7\xa4\xba' 51463
b' ADHD' 51464

**Comment by LiuShixing** [comment]
> 您好，这不是bug，是tokenizer的原理导致 —— 单个 token 并不一定对应任何字词，有时候需要多个 tokens 组合才能构成合法的字词 —— 因此会出现您观察到的 “后面有接其他字符就恢复正常” 现象。如果完全生成结束后，依然有乱码，才是 bug。
> 
> 一种较简单的解决方法就是在未完全生成结束前，先简单过滤掉 response 末尾的非法字符。

你好，怎么过滤比较好呢

**Comment by JianxinMa** [comment]
> > 您好，这不是bug，是tokenizer的原理导致 —— 单个 token 并不一定对应任何字词，有时候需要多个 tokens 组合才能构成合法的字词 —— 因此会出现您观察到的 “后面有接其他字符就恢复正常” 现象。如果完全生成结束后，依然有乱码，才是 bug。
> > 一种较简单的解决方法就是在未完全生成结束前，先简单过滤掉 response 末尾的非法字符。
> 
> 你好，怎么过滤比较好呢

新的代码应该已经没有乱码了，请更新下代码再试试。注意：除了github代码，hugginface那边的代码也需要重新执行 from_pretrained 拉取下新代码。

**Comment by abc20220327** [comment]
> > > 您好，这不是bug，是tokenizer的原理导致 —— 单个 token 并不一定对应任何字词，有时候需要多个 tokens 组合才能构成合法的字词 —— 因此会出现您观察到的 “后面有接其他字符就恢复正常” 现象。如果完全生成结束后，依然有乱码，才是 bug。
> > > 一种较简单的解决方法就是在未完全生成结束前，先简单过滤掉 response 末尾的非法字符。
> > 
> > 
> > 你好，怎么过滤比较好呢
> 
> 新的代码应该已经没有乱码了，请更新下代码再试试。注意：除了github代码，hugginface那边的代码也需要重新执行 from_pretrained 拉取下新代码。

麻烦告知改了什么地方

**Comment by LouisHeck** [comment]
> 流失会导致结尾出现非法字符



> 

请问你知道官方改动了哪里吗？怎么可以过滤掉当前生成的token，而且还能将当前token保留下去，并与下一个token合并来解码，麻烦了

**Comment by JianxinMa** [comment]
> > 流失会导致结尾出现非法字符
> 
> > 
> 
> 请问你知道官方改动了哪里吗？怎么可以过滤掉当前生成的token，而且还能将当前token保留下去，并与下一个token合并来解码，麻烦了

似乎是 tokenizer.decode(output, errors="ignore") 配了 errors="ignore" 就解决了

**Comment by LouisHeck** [comment]
> > > 流失会导致结尾出现非法字符
> > 
> > 
> > > 
> > 
> > 
> > 请问你知道官方改动了哪里吗？怎么可以过滤掉当前生成的token，而且还能将当前token保留下去，并与下一个token合并来解码，麻烦了
> 
> 似乎是 tokenizer.decode(output, errors="ignore") 配了 errors="ignore" 就解决了
感谢回答，根据你提供的"ignore"关键字，查找了下仓库，发现[tokenization_note_zh.md](https://github.com/QwenLM/Qwen-7B/blob/1f2aaa8cf8dd85452ce211c5345cb7de3d5f0f9d/tokenization_note_zh.md?plain=1#L19)有介绍。

```
## 普通token

普通token源于BPE，是在UTF-8编码的文本字节序列上学习得到的。
尽管基于字节序列的方式保证了所有文本均可被tokenize且没有未登录token问题，但处理罕见文本时有可能回退到字节级别的编码。
由于从字节序列解码为文本时，`errors`参数设为`replace`，处理不完整的token序列可能会遇到UTF-8解码错误，表象是生成中包含“替换字符”(�)。
这一行为可以通过将`errors`参数设为`ignore`来规避。
一次性修改可以传入tokenizer的`decode`函数，持久性修改可以传入tokenizer的初始化函数，请注意`decode`的配置优先级更高。
`errors`的可选值，请参阅[Python文档](https://docs.python.org/3/library/stdtypes.html#bytes.decode).

```python
>>> tokenizer.decode([51461])
' �'

>>> tokenizer.convert_ids_to_tokens([51461])
[b' \xe6\xa0']

>>> b' \xe6\xa0'.decode("utf-8", errors='replace')
' �'

>>> tokenizer.decode([51461, 117])
' 根'

>>> tokenizer.convert_ids_to_tokens([51461, 117])
[b' \xe6\xa0', b'\xb9']

>>> b' \xe6\xa0\xb9'.decode("utf-8", errors='replace')
' 根'
```

`bytes`类型的普通token到id的映射可以通过`tokenizer.get_vocab()`获取。
尚不支持也不推荐向tokenizer增加普通token。

再次感谢回答

**Comment by qyccc** [comment]
请教一下，这个bpe和bbpe有什么区别吗
