### ISSUE TITLE
支持量化的Qwen stream/batch推理，int8单卡显存9g，int4单卡显存6G可跑

### ISSUE THREAD

**Issue by Tongjilibo** [QwenLM/Qwen-7B#94]
自研[bert4torch](https://github.com/Tongjilibo/bert4torch)框架，加入了Qwen的量化推理[Qwen推理示例](https://github.com/Tongjilibo/bert4torch/blob/master/examples/basic/basic_language_model_Qwen.py), 有兴趣的小伙伴可以试用一下

**Comment by geekinglcq** [comment]
Hi，你好～ 能详细说一下bert4torch的量化算法和实现嘛？因为我在这个示例里没找到量化部分的代码，第33行看起来有个`model = model.quantize`，但是被注释了。

**Comment by Tongjilibo** [comment]
可以解开注释跑，示例中的是参考的chatglm的cpm_kernel方式，也可以使用其他量化方式

**Comment by vbkjichs290** [comment]
厉害呀，支持下、！

**Comment by YiTouch** [comment]
老哥，Qwen用这个6G显存真的能跑吗？试了一下还是CUDA out of memory😭

**Comment by vbkjichs290** [comment]
> 老哥，Qwen用这个6G显存真的能跑吗？开了量化注释int4，启动后输入提问，马上报错CUDA out of memory😭

不行，我的是10G的版本，实测正常使用至少要7GB,运行一段时间甚至回到9.9G

**Comment by Tongjilibo** [comment]
运行的越久，是显存占用的越大的，我在6g显存下，有正常输出过句子，但是要玩转的话还是显存要更大一些的
