### ISSUE TITLE
[BUG] <有使用swiglu激活码>

### ISSUE THREAD

**Issue by Tongjilibo** [QwenLM/Qwen-7B#95]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

config.json中有写激活函数是用的swiglu，但是模型结构中没看到该激活，只看到silu，是不是多写了这个参数呢？

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JustinLin610** [comment]
swiglu在这里是silu(w1x+b1) * (w2x+b2)的形式，其中swish部分直接用的F.silu

**Comment by Tongjilibo** [comment]
> swiglu在这里是silu(w1x+b1) * (w2x+b2)的形式，其中swish部分直接用的F.silu

嗯嗯是的，那config中这个参数应该是没起到作用的吧，感觉可以去掉，因为本来就写死在代码里面了

**Comment by yangapku** [comment]
您好，我们已经更新config并将其去掉了哈。
