### ISSUE TITLE
[BUG] 模型generate函数，参数没有与transformers库对齐

### ISSUE THREAD

**Issue by LZHgrla** [QwenLM/Qwen-7B#96]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [x] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

`streamer`参数被传给了`assistant_model `

Qwen:
https://huggingface.co/Qwen/Qwen-7B/blob/4d36b10753ea39027a8a476bff85363dff86844e/modeling_qwen.py#L1058

Transformers: https://github.com/huggingface/transformers/blob/5f3efdf762a5de89d354879d3d6bed689bbc73b7/src/transformers/generation/utils.py#L1160

### 期望行为 | Expected Behavior

generate的key-value对齐

### 复现方法 | Steps To Reproduce

model.generate(streamer=XXX)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by neoyxm** [comment]
我碰到以下错误， 不知道是不是和楼主一个问题：
```
    response, history = self._model.chat(
  File "/home/neo/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 897, in chat
    outputs = self.generate(
  File "/home/neo/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 943, in generate
    return super().generate(
  File "/home/neo/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: generate() takes from 1 to 7 positional arguments but 8 were given
```

**Comment by littlerookie** [comment]
> 我碰到以下错误， 不知道是不是和楼主一个问题：
> 
> ```
>     response, history = self._model.chat(
>   File "/home/neo/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 897, in chat
>     outputs = self.generate(
>   File "/home/neo/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 943, in generate
>     return super().generate(
>   File "/home/neo/anaconda3/envs/chatglm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
> TypeError: generate() takes from 1 to 7 positional arguments but 8 were given
> ```

这个应该是transformers的版本低了，你试试安装4.31.0试试

**Comment by neoyxm** [comment]
@littlerookie  
谢谢啦，是这个版本问题
