### ISSUE TITLE
[BUG] <title>使用官方提供的demo.py 运行 ，输出的结果完全不对

### ISSUE THREAD

**Issue by shuoshuo0** [QwenLM/Qwen-7B#98]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [x] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

我使用官方提供的demo.py 
![image](https://github.com/QwenLM/Qwen-7B/assets/99659990/ebac256d-01c6-4459-a729-c75b6f10d188)
把问题改成了 ‘你是谁’ 他的输出是好多毫不相关的东西

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianxinMa** [comment]
您好，这个脚本跑的是base模型的demo。请不要使用 demo.py，请使用 cli_demo.py，那个才是 chat 模型的 demo~

**Comment by jiaigo** [comment]
是昨天在huggingface Qwen-7B-Chat下载的模型，当时看到的是一个大的15G的模型，现在看huggingface上的模型文件似乎与昨天有异，我先重新拉一下
